{
 "title": "MS SQL servers",
 "description": "Dashboard for Microsoft SQL server with Prometheus and Telegraf SQL plugin version 2.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sql_instance",
    "label": "SQL instance",
    "query": {
     "query": "label_values(sqlserver_server_properties_uptime,sql_instance)"
    }
   },
   {
    "name": "database_name",
    "label": "Database",
    "query": {
     "query": "label_values(sqlserver_database_io_read_bytes{sql_instance=~\"$sql_instance\"}, database_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_cpu_count{sql_instance=~\"$sql_instance\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_server_memory{sql_instance=~\"$sql_instance\"}"
    }
   ]
  },
  {
   "title": "SQL uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_uptime{sql_instance=~\"$sql_instance\"}"
    }
   ]
  },
  {
   "title": "SQL Version",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sqlserver_server_properties_engine_edition{sql_instance=~\"$sql_instance\"}",
     "legendFormat": "{{ sql_version }} {{ sku }} "
    }
   ]
  },
  {
   "title": "Online databases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_online{sql_instance=~\"$sql_instance\"}"
    }
   ]
  },
  {
   "title": "Offline databases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_offline{sql_instance=~\"$sql_instance\"}"
    }
   ]
  },
  {
   "title": "Bad databases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_recovering{sql_instance=~\"$sql_instance\"}+sqlserver_server_properties_db_recoveryPending{sql_instance=~\"$sql_instance\"}+sqlserver_server_properties_db_suspect{sql_instance=~\"$sql_instance\"}+sqlserver_server_properties_db_restoring{sql_instance=~\"$sql_instance\"}"
    }
   ]
  },
  {
   "title": "Global requests per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance_value{sql_instance=~\"$sql_instance\",counter=\"Batch Requests/sec\"}[5m]))",
     "legendFormat": "Batch Requests/sec"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance{sql_instance=~\"$sql_instance\",counter=\"SQL Compilations/sec\"}[5m]))",
     "legendFormat": "SQL Compilations/sec"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance{sql_instance=~\"$sql_instance\",counter=\"SQL Re-Compilations/sec\"}[5m]))",
     "legendFormat": "SQL Re-Compilations/sec"
    }
   ]
  },
  {
   "title": "Buffer cache hit ratio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (sqlserver_performance{sql_instance=~\"$sql_instance\",counter=\"Buffer cache hit ratio\"})",
     "legendFormat": "Buffer cache hit ratio"
    }
   ]
  },
  { "title": "DB filtered metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Database size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (sqlserver_performance_value{sql_instance=~\"$sql_instance\",instance=~\"$database_name\",counter=\"Data File(s) Size (KB)\",exported_instance!=\"Total\"})",
     "legendFormat": "Data"
    },
    {
     "expr": "sum by (sql_instance) (sqlserver_performance_value{sql_instance=~\"$sql_instance\",instance=~\"$database_name\",counter=\"Log File(s) Size (KB)\",exported_instance!=\"Total\"})",
     "legendFormat": "TLog"
    }
   ]
  },
  {
   "title": "Transactions per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance_value{sql_instance=~\"$sql_instance\",instance=~\"$database_name\",counter=\"Transactions/sec\",exported_instance!=\"Total\"}[5m]))",
     "legendFormat": "1/s"
    }
   ]
  },
  {
   "title": "Database IO throughout",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_read_bytes{sql_instance=~\"$sql_instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_write_bytes{sql_instance=~\"$sql_instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Database IO operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_reads{sql_instance=~\"$sql_instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_writes{sql_instance=~\"$sql_instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Database IO latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_read_latency_ms{sql_instance=~\"$sql_instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Read latency"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_write_latency_ms{sql_instance=~\"$sql_instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Write latency"
    }
   ]
  },
  {
   "title": "Backup/restore throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance_value{sql_instance=~\"$sql_instance\",instance=~\"$database_name\",counter=\"Backup/Restore Throughput/sec\",instance!=\"Total\"}[5m]))",
     "legendFormat": "Backup/Restore Throughput/sec"
    }
   ]
  }
 ]
}