{
 "title": "SQL Server Monitoring - Advanced",
 "description": "Monitoring SQL Servers using Telegraf and Prometheus",
 "tags": [
  "prometheus",
  "SQL Server"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(sql_instance)" } },
   {
    "name": "database_name",
    "query": {
     "query": "label_values(sqlserver_database_io_read_bytes{sql_instance=~\"$instance\"}, database_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Databases properties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "DATABASES HEALTH",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_server_properties_db_offline{sql_instance=~\"^$instance\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "State OFFLINE",
       "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
       ]
      }
     ]
    },
    {
     "title": "ONLINE",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_server_properties_db_online{sql_instance=~\"^$instance\"}",
       "measurement": "State ONLINE",
       "query": "SELECT \"total\" FROM \"State ONLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
       ]
      }
     ]
    },
    {
     "title": "OFFLINE",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_server_properties_db_offline{sql_instance=~\"^$instance\"}",
       "measurement": "State OFFLINE",
       "query": "SELECT \"total\" FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
       ]
      }
     ]
    },
    {
     "title": "SUSPECT",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_server_properties_db_suspect{sql_instance=~\"^$instance\"}",
       "measurement": "State SUSPECT",
       "query": "SELECT \"total\" FROM \"State SUSPECT\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
       ]
      }
     ]
    },
    {
     "title": "RECOVERING",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_server_properties_db_recovering{sql_instance=~\"^$instance\"}",
       "measurement": "State RECOVERING",
       "query": "SELECT \"total\" FROM \"State RECOVERING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
       ]
      }
     ]
    },
    {
     "title": "PENDING",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_server_properties_db_recoveryPending{sql_instance=~\"^$instance\"}",
       "measurement": "State RECOVERY_PENDING",
       "query": "SELECT \"total\" FROM \"State RECOVERY_PENDING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
       ]
      }
     ]
    },
    {
     "title": "RESTORING",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_server_properties_db_restoring{sql_instance=~\"^$instance\"}",
       "measurement": "State RESTORING",
       "query": "SELECT \"total\" FROM \"State RESTORING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
       ]
      }
     ]
    },
    {
     "title": "Total Data File Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_performance_value{counter=~\"Data File.*Size.*\",instance=~\".*Total\",sql_instance=~\"^$instance\"}",
       "measurement": "Performance metrics",
       "query": "SELECT \"Point In Time Recovery\" FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter",
       "select": [
        [
         { "params": [ "Point In Time Recovery" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
       ]
      }
     ]
    },
    {
     "title": "Total Log Files Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_performance_value{counter=\"Log File(s) Size (KB)\",instance=\"Total\",sql_instance=~\"^$instance\"}",
       "measurement": "Recovery Model BULK_LOGGED",
       "query": "SELECT \"total\" FROM \"Recovery Model BULK_LOGGED\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
       ]
      }
     ]
    },
    {
     "title": "Memory Clerk Buffer Pool",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sqlserver_memory_clerks_size_kb{clerk_type=\"Buffer Pool\",sql_instance=~\"^$instance\"}"
      }
     ]
    },
    {
     "title": "Total Log Files Used Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 14, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_performance_value{counter=\"Log File(s) Used Size (KB)\",instance=\"Total\",sql_instance=~\"^$instance\"}",
       "measurement": "Recovery Model FULL",
       "query": "SELECT \"total\" FROM \"Recovery Model FULL\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
       ]
      }
     ]
    },
    {
     "title": "CPU Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_server_properties_cpu_count{sql_instance=~\"^$instance\"}",
       "measurement": "Recovery Model SIMPLE",
       "query": "SELECT \"total\" FROM \"Recovery Model SIMPLE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Total Server Memory (KB)\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Target Server Memory (KB) | Memory Manager",
     "query": "SELECT mean(\"value\") FROM \"Target Server Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Used memory (KB)\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Total Server Memory (KB) | Memory Manager",
     "query": "SELECT mean(\"value\") FROM \"Total Server Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "User Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"User Connections\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "User Connections | General Statistics",
     "query": "SELECT mean(\"value\") FROM \"User Connections | General Statistics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Buffer cache hit ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Buffer cache hit ratio\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Buffer pool rate (bytes/sec)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Buffer pool rate (bytes/sec)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "Memory Grant Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Memory Grants Pending\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Memory Grants Pending | Memory Manager",
     "query": "SELECT mean(\"value\") FROM \"Memory Grants Pending | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Checkpoint pages/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Checkpoint pages/sec\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Connection memory per connection (bytes)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "Connection memory per connection (bytes)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "Free List Stalls/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Free list stalls/sec\",sql_instance=~\"^$instance\"}",
     "measurement": "Free list stalls/sec | Buffer Manager",
     "query": "SELECT \"value\" FROM \"Free list stalls/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Page lookups/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(sqlserver_performance_value{counter=\"Page lookups/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Total target memory ratio\") FROM \"Performance metrics\" WHERE \"type\" = 'Performance metrics' AND \"servername\" =~ /$Instance$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Total target memory ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Performance metrics" },
      { "condition": "AND", "key": "servername", "operator": "=~", "value": "/$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Free Space in tempdb",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Free Space in tempdb (KB)\",sql_instance=~\"^$instance\"}",
     "measurement": "Data File(s) Size (KB) | mssqlsystemresource | Databases",
     "query": "SELECT \"value\" FROM \"Data File(s) Size (KB) | mssqlsystemresource | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Version Store Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Version Store Size (KB)\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Percent Log Used | mssqlsystemresource | Databases",
     "query": "SELECT mean(\"value\") FROM \"Percent Log Used | mssqlsystemresource | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "PLE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Page life expectancy\",object=\"SQLServer:Buffer Manager\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Page life expectancy | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Page life expectancy | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Backup/Restore Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Backup/Restore Throughput/sec\",instance=\"Total\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Backup/Restore Throughput/sec | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Backup/Restore Throughput/sec | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Active Temp Tables",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Active Temp Tables\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Page File Usage (%)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Page File Usage (%)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Database size trend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database | Rows Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "alias": "$col",
       "expr": "sqlserver_performance_value{counter=\"Data File(s) Size (KB)\",sql_instance=~\"^$instance\"}",
       "legendFormat": "{{instance}}",
       "measurement": "Rows size (bytes)",
       "query": "SELECT * FROM \"Rows size (bytes)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database size' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database size" }
       ]
      }
     ]
    },
    {
     "title": "Database | Log Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "alias": "$col",
       "expr": "sqlserver_performance_value{counter=\"Log File(s) Size (KB)\",sql_instance=~\"^$instance\"}",
       "legendFormat": "{{instance}}",
       "measurement": "Log size (bytes)",
       "query": "SELECT * FROM \"Log size (bytes)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database size' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database size" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory break down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used memory by Instance",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col",
       "expr": "rate(sqlserver_performance_value{counter=~\"Used memory.*\",instance=~\".*Master\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{instance}}",
       "measurement": "Memory breakdown (%)",
       "query": "SELECT * FROM \"Memory breakdown (%)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Memory clerk' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Memory clerk" }
       ]
      }
     ]
    },
    {
     "title": "Memory Clerks Size",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "irate(sqlserver_memory_clerks_size_kb{clerk_type=~\"^SQL.*\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{clerk_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO/sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(sqlserver_performance_value{counter=~\"^Disk.*IO.*\",instance=\"internal\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{counter}}"
      }
     ]
    },
    {
     "title": "DATA | Read Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(sqlserver_database_io_read_bytes{file_type=\"DATA\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{database_name}}",
       "measurement": "Rows reads (bytes/sec)",
       "query": "SELECT \"AdventureWorks2014\", \"Australian\", \"DOC.Azure\", \"ResumeCloud\", \"ngMon\", \"tempdb\" FROM \"Rows reads (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
       ]
      }
     ]
    },
    {
     "title": "LOG | Read Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(sqlserver_database_io_read_bytes{file_type=\"LOG\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{database_name}}",
       "measurement": "Log reads (bytes/sec)",
       "query": "SELECT \"AdventureWorks2014\", \"Australian\", \"DOC.Azure\", \"ResumeCloud\", \"ngMon\", \"tempdb\" FROM \"Log reads (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
       ]
      }
     ]
    },
    {
     "title": "DATA | Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(sqlserver_database_io_write_bytes{file_type=\"DATA\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{database_name}}",
       "measurement": "Rows writes (bytes/sec)",
       "query": "SELECT \"AdventureWorks2014\", \"Australian\", \"DOC.Azure\", \"ResumeCloud\", \"ngMon\", \"tempdb\" FROM \"Rows writes (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
       ]
      }
     ]
    },
    {
     "title": "LOG | Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(sqlserver_database_io_write_bytes{file_type=\"LOG\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{database_name}}",
       "measurement": "Log reads (bytes/sec)",
       "query": "SELECT \"AdventureWorks2014\", \"Australian\", \"DOC.Azure\", \"ResumeCloud\", \"ngMon\", \"tempdb\" FROM \"Log reads (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Database Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "DATA | Read Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(sqlserver_database_io_read_latency_ms{file_type=\"DATA\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{database_name}}",
       "measurement": "Rows read latency (ms)",
       "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database stats' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database stats" }
       ]
      }
     ]
    },
    {
     "title": "LOG | Read Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(sqlserver_database_io_read_latency_ms{file_type=\"LOG\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{database_name}}",
       "measurement": "Log read latency (ms)",
       "query": "SELECT * FROM \"Log read latency (ms)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database stats' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database stats" }
       ]
      }
     ]
    },
    {
     "title": "DATA | Write Latency (ms)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(sqlserver_database_io_write_latency_ms{file_type=\"DATA\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{database_name}}",
       "measurement": "Rows read latency (ms)",
       "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database stats' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database stats" }
       ]
      }
     ]
    },
    {
     "title": "LOG | Write Latency (ms)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(sqlserver_database_io_write_latency_ms{file_type=\"LOG\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{database_name}}",
       "measurement": "Log read latency (ms)",
       "query": "SELECT * FROM \"Log read latency (ms)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database stats' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database stats" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Waits Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wait Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(sqlserver_waitstats_wait_time_ms{sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{wait_category}} {{wait_type}}"
      }
     ]
    },
    {
     "title": "Wait Tasks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(sqlserver_waitstats_waiting_tasks_count{sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{wait_category}} {{wait_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Availability Replica",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "OUT | Bytes sent to Replica/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(sqlserver_performance_value{counter=\"Bytes Sent to Replica/sec\",instance=~\".*Total|.*Master\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{counter}}",
       "measurement": "Bytes Sent to Replica/sec | _Total | Availability Replica",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Performance counters" },
        { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "IN | Bytes received from Replica/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(sqlserver_performance_value{counter=\"Bytes Received from Replica/sec\",instance=~\".*Total|.*Master\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{counter}}",
       "measurement": "Bytes Received from Replica/sec | _Total | Availability Replica",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Performance counters" },
        { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Transaction Delay",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sqlserver_performance_value{counter=\"Transaction Delay\",instance=~\".*Total|.*Master\",sql_instance=~\"^$instance\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{host}}",
       "measurement": "Transaction Delay | _Total | Database Replica",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Performance counters" },
        { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Mirrored Write Transactions/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(sqlserver_performance_value{counter=\"Mirrored Write Transactions/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{servername}}",
       "measurement": "Mirrored Write Transactions/sec | _Total | Database Replica",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Performance counters" },
        { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Performance counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "SQL Server Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(sqlserver_performance_value{counter=\"Batch Requests/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Batch Requests/sec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "irate(sqlserver_performance_value{counter=\"Logins/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Logins/sec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "irate(sqlserver_performance_value{counter=\"Logouts/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Logouts/sec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "irate(sqlserver_performance_value{counter=\"SQL Compilations/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "SQL Compilations/sec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "irate(sqlserver_performance_value{counter=\"SQL Re-Compilations/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "SQL Re-Compilations/sec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "irate(sqlserver_performance_value{counter=\"Processes blocked\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Processes blocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Databases Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Transactions/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Transactions/sec\",database_name=\"master\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Transactions/sec",
     "measurement": "Transactions/sec | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Transactions/sec | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Write Transactions/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Write Transactions/sec\",database_name=\"master\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Write Transactions/sec",
     "measurement": "Write Transactions/sec | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Write Transactions/sec | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Log Flushes/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Log Flushes/sec\",database_name=\"master\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Log Flushes/sec",
     "measurement": "Log Flushes/sec | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Log Flushes/sec | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Log Flush Wait Time",
     "expr": "irate(sqlserver_performance_value{counter=\"Log Flush Wait Time\",database_name=\"master\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Log Flush Wait Time",
     "measurement": "Log Flush Wait Time | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Log Flush Wait Time | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Lock Timeouts/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Lock Timeouts/sec\",database_name=\"master\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Lock Timeouts/sec",
     "measurement": "Lock Timeouts/sec | _Total | Locks",
     "query": "SELECT mean(\"value\") FROM \"Lock Timeouts/sec | _Total | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Number of Deadlocks/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Number of Deadlocks/sec\",database_name=\"master\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Number of Deadlocks/sec",
     "measurement": "Number of Deadlocks/sec | _Total | Locks",
     "query": "SELECT mean(\"value\") FROM \"Number of Deadlocks/sec | _Total | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Lock Waits/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Lock Waits/sec\",database_name=\"master\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Lock Waits/sec",
     "measurement": "Lock Waits/sec | _Total | Locks",
     "query": "SELECT mean(\"value\") FROM \"Lock Waits/sec | _Total | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Latch Waits/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Latch Waits/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Latch Waits/sec",
     "measurement": "Latch Waits/sec | Latches",
     "query": "SELECT mean(\"value\") FROM \"Latch Waits/sec | Latches\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Cache - Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Full Scans/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Full Scans/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Full Scans/sec",
     "measurement": "Full Scans/sec | Access Methods",
     "query": "SELECT mean(\"value\") FROM \"Full Scans/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Index Searches/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Index Searches/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Index Searches/sec",
     "measurement": "Index Searches/sec | Access Methods",
     "query": "SELECT mean(\"value\") FROM \"Index Searches/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Page Splits/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Page Splits/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Page Splits/sec",
     "measurement": "Page Splits/sec | Access Methods",
     "query": "SELECT mean(\"value\") FROM \"Page Splits/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Page lookups/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Page lookups/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Page lookups/sec",
     "measurement": "Page lookups/sec | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Page lookups/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Page reads/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Page reads/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Page reads/sec",
     "measurement": "Page reads/sec | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Page reads/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Page writes/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Page writes/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Page writes/sec",
     "measurement": "Page writes/sec | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Page writes/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Readahead pages/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Readahead pages/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Readahead pages/sec",
     "measurement": "Readahead pages/sec | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Readahead pages/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Lazy writes/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Lazy writes/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Lazy writes/sec",
     "measurement": "Lazy writes/sec | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Lazy writes/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Checkpoint pages/sec",
     "expr": "irate(sqlserver_performance_value{counter=\"Checkpoint pages/sec\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Checkpoint pages/sec",
     "measurement": "Checkpoint pages/sec | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Checkpoint pages/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Memory Manager",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "SQL Cache",
     "expr": "sqlserver_memory_clerks_size_kb{clerk_type=\"Transactions Cache (Object Store)\",sql_instance=~\"^$instance\"}",
     "legendFormat": "SQL Cache",
     "measurement": "SQL Cache Memory (KB) | Memory Manager",
     "query": "SELECT \"value\" FROM \"SQL Cache Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Optimizer",
     "expr": "sqlserver_memory_clerks_size_kb{clerk_type=\"SQL Optimizer\",sql_instance=~\"^$instance\"}",
     "legendFormat": "Optimizer",
     "measurement": "Optimizer Memory (KB) | Memory Manager",
     "query": "SELECT \"value\" FROM \"Optimizer Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Log Pool",
     "expr": "sqlserver_memory_clerks_size_kb{clerk_type=\"Log Pool\",sql_instance=~\"^$instance\"}",
     "legendFormat": "Log Pool",
     "measurement": "Log Pool Memory (KB) | Memory Manager",
     "query": "SELECT \"value\" FROM \"Log Pool Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Lock",
     "expr": "Lock_Memory__KB____Memory_Manager{sql_instance=~\"^$instance\"}",
     "legendFormat": "Lock",
     "measurement": "Lock Memory (KB) | Memory Manager",
     "query": "SELECT \"value\" FROM \"Lock Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Database Cache",
     "expr": "Database_Cache_Memory__KB____Memory_Manager{sql_instance=~\"^$instance\"}",
     "legendFormat": "Database Cache",
     "measurement": "Database Cache Memory (KB) | Memory Manager",
     "query": "SELECT \"value\" FROM \"Database Cache Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Connection",
     "expr": "Connection_Memory__KB____Memory_Manager{sql_instance=~\"^$instance\"}",
     "legendFormat": "Connection",
     "measurement": "Connection Memory (KB) | Memory Manager",
     "query": "SELECT \"value\" FROM \"Connection Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  }
 ]
}