{
 "title": "CloudWatch - API Gateway",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ApiName", "query": { "query": "label_values(ApiName)" } },
   { "name": "Stage", "query": { "query": "label_values(Stage)" } }
  ]
 },
 "panels": [
  {
   "title": "4XX Errors Count ($Stage)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(amazonaws_com_AWS_ApiGateway_4XXError{ApiName=~\"$ApiName\",Stage=~\"$Stage\",ApiName!=\"\"}) by (ApiName,Method)",
     "legendFormat": "4XX Error - {{ApiName}}-{{Method}}"
    }
   ]
  },
  {
   "title": "5XX Errors Count ($Stage)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(amazonaws_com_AWS_ApiGateway_5XXError{ApiName=~\"$ApiName\",Stage=~\"$Stage\",ApiName!=\"\"}) by (ApiName,Method)",
     "legendFormat": "5XX Error - {{ApiName}}{{Method}}"
    }
   ]
  },
  {
   "title": "Sum of API Request Count by Resource",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_ApiGateway_Count{ApiName=~\"$ApiName\",Stage=~\"$Stage\",ApiName!=\"\"}) by (ApiName, Resource)",
     "legendFormat": "{{ApiName}}-{{Resource}}"
    }
   ]
  },
  {
   "title": "Average Latency by API Resource",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_ApiGateway_Latency{ApiName=~\"$ApiName\",Stage=~\"$Stage\",ApiName!=\"\",Resource!=\"\",quantile=\"1\"}) by (ApiName,Resource)",
     "legendFormat": "{{ApiName}}-{{Resource}}"
    }
   ]
  },
  {
   "title": "Average Integration Latency by API Resource",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_ApiGateway_IntegrationLatency{ApiName=~\"$ApiName\",Stage=~\"$Stage\",ApiName!=\"\",Resource!=\"\",quantile=\"1\"}) by (ApiName,Resource)",
     "legendFormat": "{{ApiName}}-{{Resource}}"
    }
   ]
  }
 ]
}