{
 "title": "CloudWatch - Application Load Balancer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "loadbalancername", "label": "Load Balancer Name", "query": { "query": "label_values(LoadBalancer)" } }
  ]
 },
 "panels": [
  {
   "title": "RequestCount / TargetResponseTime / Host Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_ApplicationELB_RequestCount{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "RequestCount_Average"
    },
    {
     "expr": "avg(amazonaws_com_AWS_ApplicationELB_TargetResponseTime{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "TargetResponseTime_Average"
    },
    {
     "expr": "avg(amazonaws_com_AWS_ApplicationELB_HealthyHostCount{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "HealthyHostCount_Average"
    },
    {
     "expr": "avg(amazonaws_com_AWS_ApplicationELB_UnHealthyHostCount{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "UnHealthyHostCount_Average"
    }
   ]
  },
  {
   "title": "HTTPCode_Target",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_ApplicationELB_HTTPCode_Target_5XX_Count{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "HTTPCode_Target_5XX_Count_Average"
    },
    {
     "expr": "sum(amazonaws_com_AWS_ApplicationELB_HTTPCode_Target_4XX_Count{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "HTTPCode_Target_4XX_Count_Average"
    },
    {
     "expr": "sum(amazonaws_com_AWS_ApplicationELB_HTTPCode_Target_3XX_Count{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "HTTPCode_Target_3XX_Count_Average"
    },
    {
     "expr": "sum(amazonaws_com_AWS_ApplicationELB_HTTPCode_Target_2XX_Count{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "HTTPCode_Target_2XX_Count_Average"
    }
   ]
  },
  {
   "title": "ConnectionCount",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_ApplicationELB_ActiveConnectionCount{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "ActiveConnectionCount_Average"
    },
    {
     "expr": "avg(amazonaws_com_AWS_ApplicationELB_NewConnectionCount{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "NewConnectionCount_Average"
    },
    {
     "expr": "avg(amazonaws_com_AWS_ApplicationELB_RejectedConnectionCount{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "RejectedConnectionCount_Average"
    },
    {
     "expr": "avg(amazonaws_com_AWS_ApplicationELB_TargetConnectionErrorCount{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "TargetConnectionErrorCount_Average"
    }
   ]
  },
  {
   "title": "ConsumedLBCapacityUnits / ConsumedLCUs / ProcessedBytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_ApplicationELB_ConsumedLBCapacityUnits{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "ConsumedLBCapacityUnits_Average"
    },
    {
     "expr": "avg(amazonaws_com_AWS_ApplicationELB_ConsumedLCUs{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "ConsumedLCUs_Average"
    },
    {
     "expr": "avg(amazonaws_com_AWS_ApplicationELB_ProcessedBytes{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "ProcessedBytes_Average"
    }
   ]
  },
  {
   "title": "TLSNegotiationErrorCount",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_ApplicationELB_TargetTLSNegotiationErrorCount{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "TargetTLSNegotiationErrorCount_Sum"
    },
    {
     "expr": "sum(amazonaws_com_AWS_ApplicationELB_ClientTLSNegotiationErrorCount{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "ClientTLSNegotiationErrorCount_Sum"
    }
   ]
  },
  {
   "title": "RuleEvaluations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_ApplicationELB_RuleEvaluations{LoadBalancer=\"$loadbalancername\"})",
     "legendFormat": "RuleEvaluations_Sum"
    }
   ]
  }
 ]
}