{
 "title": "CloudWatch - Aurora",
 "time": { "from": "2022-11-06T09:40:32.086Z", "to": "2022-11-06T15:40:32.086Z" },
 "templating": {
  "list": [
   {
    "name": "instance_max_connections",
    "label": "Instance Type",
    "query": "db.t2.small : 45,db.t2.medium : 90,db.t3.small : 45,db.t3.medium : 90,db.t3.large : 135,db.t4g.medium : 90,db.t4g.large : 135,db.r3.large : 1000,db.r3.xlarge : 2000,db.r3.2xlarge : 3000,db.r3.4xlarge : 4000,db.r3.8xlarge : 5000,db.r4.large : 1000,db.r4.xlarge : 2000,db.r4.2xlarge : 3000,db.r4.4xlarge : 4000,db.r4.8xlarge : 5000,db.r4.16xlarge : 6000,db.r5.large : 1000,db.r5.xlarge : 2000,db.r5.2xlarge : 3000,db.r5.4xlarge : 4000,db.r5.8xlarge : 5000,db.r5.12xlarge : 6000,db.r5.16xlarge : 6000,db.r5.24xlarge : 7000,db.r6g.large : 1000,db.r6g.xlarge : 2000,db.r6g.2xlarge : 3000,db.r6g.4xlarge : 4000,db.r6g.8xlarge : 5000,db.r6g.12xlarge : 6000,db.r6g.16xlarge : 6000,db.x2g.large : 2000,db.x2g.xlarge : 3000,db.x2g.2xlarge : 4000,db.x2g.4xlarge : 5000,db.x2g.8xlarge : 6000,db.x2g.12xlarge : 7000,db.x2g.16xlarge : 7000"
   },
   { "name": "role", "label": "Role", "query": { "query": "label_values(Role)" } }
  ]
 },
 "panels": [
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Used Max Connections",
   "type": "stat",
   "description": "Percentage of the maximum connections as stated by the Instance Type.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(amazonaws_com_AWS_RDS_DatabaseConnections{Role=~\"$role\"}) by (Role) / $instance_max_connections",
     "legendFormat": "{{Role}}"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(amazonaws_com_AWS_RDS_VolumeBytesUsed{EngineName=\"aurora-mysql\"} ) / (max(amazonaws_com_AWS_RDS_VolumeBytesUsed{EngineName=\"aurora-mysql\"}) + max(amazonaws_com_AWS_RDS_AuroraVolumeBytesLeftTotal{EngineName=\"aurora-mysql\"})) ",
     "legendFormat": "{{Role}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "ceil(sum(amazonaws_com_AWS_RDS_Queries{Role=~\"$role\"}) by (Role))",
     "legendFormat": "{{Role}}"
    }
   ]
  },
  {
   "title": "DML Latency (p95)",
   "type": "stat",
   "description": "95th percentile of RDS DML Latency (the average duration of inserts, updates, and deletes).",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.95, amazonaws_com_AWS_RDS_DMLLatency{Role=~\"$role\"})"
    }
   ]
  },
  {
   "title": "DDL Latency (p95)",
   "type": "stat",
   "description": "95th percentile of RDS DDL Latency (the average duration of requests such as example, create, alter, and drop requests).",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.95, amazonaws_com_AWS_RDS_DDLLatency{Role=~\"$role\"})"
    }
   ]
  },
  {
   "title": "Login Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(amazonaws_com_AWS_RDS_LoginFailures{Role=~\"$role\"}) by (Role)",
     "legendFormat": "{{Role}}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(amazonaws_com_AWS_RDS_Deadlocks{Role=~\"$role\"}) by (Role)"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Avg DB Connections by Role",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max(amazonaws_com_AWS_RDS_DatabaseConnections{Role=~\"$role\"}) by (Role)",
     "legendFormat": "{{Role}}"
    }
   ]
  },
  {
   "title": "Queries over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_Queries{Role=~\"$role\"}) by (Role)",
     "legendFormat": "Avg Queries"
    }
   ]
  },
  {
   "title": "Avg CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_CPUUtilization{Role=~\"$role\"}) by (Role)",
     "legendFormat": "{{Role}}"
    }
   ]
  },
  {
   "title": "Deadlocks over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "max(amazonaws_com_AWS_RDS_Deadlocks{Role=~\"$role\"}) by (Role)",
     "legendFormat": "Deadlocks"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "DDL Latency",
   "type": "timeseries",
   "description": "The average duration of requests such as example, create, alter, and drop requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_DDLLatency{Role=~\"$role\"}) by (Role)",
     "legendFormat": "Avg DDL Latency"
    }
   ]
  },
  {
   "title": "DML Latency",
   "type": "timeseries",
   "description": "The average duration of inserts, updates, and deletes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_DMLLatency{Role=~\"$role\"}) by (Role)",
     "legendFormat": "Avg DML Latency"
    }
   ]
  },
  {
   "title": "Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_CommitLatency{Role=~\"$role\"}) by (Role)",
     "legendFormat": "Avg Commit Latency"
    }
   ]
  },
  {
   "title": "Avg Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_ReadLatency{Role=~\"$role\"}) by (Role)",
     "legendFormat": "Avg Read Latency"
    },
    {
     "expr": "avg(amazonaws_com_AWS_RDS_WriteLatency{Role=~\"$role\"}) by (Role)",
     "legendFormat": "Avg Write Latency"
    }
   ]
  },
  {
   "title": "Select Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_SelectLatency{Role=~\"$role\"}) by (Role)",
     "legendFormat": "Avg Select Latency"
    }
   ]
  },
  {
   "title": "Avg Insert/Delete/Update",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_InsertLatency{Role=~\"$role\"}) by (Role)",
     "legendFormat": "Avg Insert Latency"
    },
    {
     "expr": "avg(amazonaws_com_AWS_RDS_DeleteLatency{Role=~\"$role\"}) by (Role)",
     "legendFormat": "Avg Delete Latency"
    },
    {
     "expr": "avg(amazonaws_com_AWS_RDS_UpdateLatency{Role=~\"$role\"}) by (Role)",
     "legendFormat": "Avg Update Latency"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Read IOps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_VolumeReadIOPs)",
     "legendFormat": "Read IOps"
    }
   ]
  },
  {
   "title": "Write IOps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_VolumeWriteIOPs)",
     "legendFormat": "Write IOps"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(amazonaws_com_AWS_RDS_VolumeBytesUsed{EngineName=\"aurora-mysql\"} ) / (max(amazonaws_com_AWS_RDS_VolumeBytesUsed{EngineName=\"aurora-mysql\"}) + max(amazonaws_com_AWS_RDS_AuroraVolumeBytesLeftTotal{EngineName=\"aurora-mysql\"}))",
     "legendFormat": "Disk Usage %"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Network In",
   "type": "timeseries",
   "description": "The NetworkReceiveThroughput metric tracks network traffic sent from clients. Unlike other RDS database engines, Aurora’s network metric does not include network traffic from the database instances to the storage volumes.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_NetworkReceiveThroughput{Role=~\"$role\"})",
     "legendFormat": "Network In"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "description": "The NetworkTransmitThroughput metric tracks network traffic being sent to clients. Unlike other RDS database engines, Aurora’s network metric does not include network traffic from the database instances to the storage volumes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_NetworkTransmitThroughput{Role=~\"$role\"})",
     "legendFormat": "Network Out"
    }
   ]
  }
 ]
}