{
 "title": "CloudWatch - CloudFront",
 "description": "Visualize AWS CloudFront metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DistributionId", "query": { "query": "label_values(DistributionId)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests / TotalErrorRate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "expr": "sum(amazonaws_com_AWS_CloudFront_Requests{DistributionId=\"$DistributionId\"}) ",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Requests",
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "expr": "avg(amazonaws_com_AWS_CloudFront_TotalErrorRate{DistributionId=\"$DistributionId\"})",
     "legendFormat": "ErrorRate_Average"
    }
   ]
  },
  {
   "title": "4xxErrorRate / 5xxErrorRate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "expr": "avg(amazonaws_com_AWS_CloudFront_4xxErrorRate{DistributionId=\"$DistributionId\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "4xxErrorRate_Average",
     "metricName": "4xxErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "expr": "avg(amazonaws_com_AWS_CloudFront_5xxErrorRate{DistributionId=\"$DistributionId\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "5xxErrorRate_Average",
     "metricName": "5xxErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BytesDownloaded / BytesUploaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "expr": "sum(amazonaws_com_AWS_CloudFront_BytesDownloaded{DistributionId=\"$DistributionI\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "BytesDownloaded_Average",
     "metricName": "BytesDownloaded",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "expr": "sum(amazonaws_com_AWS_CloudFront_BytesUploaded{DistributionId=\"$DistributionI\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "BytesUploaded_Average",
     "metricName": "BytesUploaded",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  }
 ]
}