{
 "title": "CloudWatch - MQ",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account",
    "label": "Account Id",
    "query": {
     "query": "label_values(amazonaws_com_AWS_AmazonMQ_AckRate,account_id)"
    }
   },
   {
    "name": "region",
    "label": "Cloud Region",
    "query": {
     "query": "label_values(amazonaws_com_AWS_AmazonMQ_AckRate{account_id=~\"$account\"},cloud_region)"
    }
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": {
     "query": "label_values(amazonaws_com_AWS_AmazonMQ_AckRate{account_id=~\"$account\"},Broker)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(amazonaws_com_AWS_Kafka_BurstBalance,Cluster_Name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Controllers by Cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_Kafka_ActiveControllerCount{account_id=~\"$account\", cloud_region=~\"$region\",quantile=\"1\"}) by (Cluster_Name)",
     "legendFormat": "{{Cluster_Name}}"
    }
   ]
  },
  {
   "title": "Burst Balance by Cluster/BrokerID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_Kafka_BurstBalance{account_id=~\"$account\",cloud_region=~\"$region\",Cluster_Name=~\"$cluster\",quantile=\"1\"}) by (Cluster_Name,Broker_ID)",
     "legendFormat": "{{Cluster_Name}}:{{Broker_ID}}"
    }
   ]
  },
  {
   "title": "Bytes In per Sec by Cluster/Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_Kafka_BytesInPerSec{account_id=~\"$account\",cloud_region=~\"$region\",Cluster_Name=~\"$cluster\",quantile=\"1\"}) by (Cluster_Name,Broker_ID)",
     "legendFormat": "{{Cluster_Name}}:{{Broker_ID}}"
    }
   ]
  },
  {
   "title": "Bytes Out per Sec by Cluster/Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_Kafka_BytesOutPerSec{account_id=~\"$account\",cloud_region=~\"$region\",Cluster_Name=~\"$cluster\",quantile=\"1\"}) by (Cluster_Name,Broker_ID)",
     "legendFormat": "{{Cluster_Name}}:{{Broker_ID}}"
    }
   ]
  },
  {
   "title": "BW In Allowance Exceeded by Cluster/Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_Kafka_BwInAllowanceExceeded{account_id=~\"$account\",cloud_region=~\"$region\",Cluster_Name=~\"$cluster\",quantile=\"1\"}) by (Cluster_Name,Broker_ID)",
     "legendFormat": "{{Cluster_Name}}:{{Broker_ID}}"
    }
   ]
  },
  {
   "title": "BW Out Allowance Exceeded by Cluster/Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_Kafka_BwOutAllowanceExceeded{account_id=~\"$account\",cloud_region=~\"$region\",Cluster_Name=~\"$cluster\",quantile=\"1\"}) by (Cluster_Name,Broker_ID)",
     "legendFormat": "{{Cluster_Name}}:{{Broker_ID}}"
    }
   ]
  },
  {
   "title": "Client Connections per Cluster/Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_Kafka_ClientConnectionCount{account_id=~\"$account\",cloud_region=~\"$region\",Cluster_Name=~\"$cluster\",quantile=\"1\"}) by (Cluster_Name,Broker_ID)",
     "legendFormat": "{{Cluster_Name}}:{{Broker_ID}}"
    }
   ]
  },
  {
   "title": "Connections per Cluster/Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_Kafka_ConnectionCount{account_id=~\"$account\",cloud_region=~\"$region\",Cluster_Name=~\"$cluster\",quantile=\"1\"}) by (Cluster_Name,Broker_ID)",
     "legendFormat": "{{Cluster_Name}}:{{Broker_ID}}"
    }
   ]
  },
  {
   "title": "Broker Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ack Rate by Broker",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "avg(amazonaws_com_AWS_AmazonMQ_AckRate{account_id=~\"$account\", cloud_region=~\"$region\",Broker=~\"$broker\",quantile=\"1\"}) by (Broker)",
       "legendFormat": "{{Broker}}"
      }
     ]
    }
   ]
  }
 ]
}