{
 "title": "CloudWatch - DB Stream",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DB Stream - Orders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Trade Orders",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count(amazonaws_com_dbstream_trade_orders_CreateLease_Success)",
       "legendFormat": "CreateLeaseSuccess_Count"
      },
      {
       "expr": "avg(amazonaws_com_dbstream_trade_orders_CreateLease_Time)",
       "legendFormat": "CreateLeaseTime_Average"
      },
      {
       "expr": "sum(amazonaws_com_dbstream_trade_orders_CurrentLeases)",
       "legendFormat": "CurrentLease_Sum"
      },
      {
       "expr": "sum(amazonaws_com_dbstream_trade_orders_ExpiredLeases)",
       "legendFormat": "ExpiredLease_Sum"
      },
      {
       "expr": "avg(amazonaws_com_dbstream_trade_orders_DataBytesProcessed)",
       "legendFormat": "DataBytesProcessed_Average"
      }
     ]
    },
    {
     "title": "Order Time by Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "avg(amazonaws_com_dbstream_trade_orders_Time{}) by (Operation)",
       "legendFormat": "OrderTime_{{Operation}}_Average"
      }
     ]
    }
   ]
  },
  {
   "title": "DB Streams - Positions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Trade Positions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "count(amazonaws_com_dbstream_trade_positions_CreateLease_Success)",
       "legendFormat": "CreatePositionsSuccess_Count"
      },
      {
       "expr": "avg(amazonaws_com_dbstream_trade_positions_CreateLease_Time)",
       "legendFormat": "CreatePositionsTime_Average"
      },
      {
       "expr": "sum(amazonaws_com_dbstream_trade_positions_CurrentLeases)",
       "legendFormat": "CurrentPositions_Sum"
      },
      {
       "expr": "sum(amazonaws_com_dbstream_trade_positions_ExpiredLeases)",
       "legendFormat": "ExpiredPositions_Sum"
      },
      {
       "expr": "avg(amazonaws_com_dbstream_trade_positions_DataBytesProcessed)",
       "legendFormat": "DataBytesProcessed_Average"
      }
     ]
    },
    {
     "title": "Positions Time by Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "avg(amazonaws_com_dbstream_trade_positions_Time{}) by (Operation)",
       "legendFormat": "PositionTime_{{Operation}}_Average"
      }
     ]
    }
   ]
  }
 ]
}