{
 "title": "CloudWatch - DynamoDB",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Max Table Level Reads: Average",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg_over_time(amazonaws_com_AWS_DynamoDB_AccountMaxTableLevelReads{quantile=\"1\"}[1m])) "
    }
   ]
  },
  {
   "title": "Max Table Level Write: Average",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(amazonaws_com_AWS_DynamoDB_AccountMaxTableLevelWrites{quantile=\"1\"}[1m])",
     "legendFormat": "{{TableName}}"
    }
   ]
  },
  {
   "title": "Provisioned Read Capacity Utilization: Average",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_DynamoDB_AccountProvisionedReadCapacityUtilization{quantile=\"1\"})"
    }
   ]
  },
  {
   "title": "Provisioned Read Capacity Utilization: Average",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_DynamoDB_AccountProvisionedReadCapacityUtilization_sum)"
    }
   ]
  },
  {
   "title": "ProvisionedReadCapacityUnits: Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_DynamoDB_SystemErrors_sum) by (Operation)",
     "legendFormat": "{{Operation}}"
    }
   ]
  },
  {
   "title": "Consumed Read Capacity Units: Sum by Table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_DynamoDB_ConsumedReadCapacityUnits{quantile=\"1\"}) by (TableName)",
     "legendFormat": "{{TableName}}"
    }
   ]
  },
  {
   "title": "Consumed Write Capacity Units: Sum by Table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_DynamoDB_ConsumedWriteCapacityUnits{quantile=\"1\"}) by (TableName)",
     "legendFormat": "{{TableName}}"
    }
   ]
  },
  {
   "title": "Returned Bytes: Average by Table and Operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_DynamoDB_ReturnedBytes_sum{}) by (TableName,Operation)",
     "legendFormat": "{{TableName}}-{{Operation}}"
    }
   ]
  },
  {
   "title": "Successful Request Latency: Average by Table and Operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_DynamoDB_SuccessfulRequestLatency{quantile=\"1\"}) by (TableName,Operation)",
     "legendFormat": "{{TableName}}-{{Operation}}"
    }
   ]
  },
  {
   "title": "amazonTTL DeletedItem Count: Average by Table",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_DynamoDB_TimeToLiveDeletedItemCount_count{}) by (TableName)",
     "legendFormat": "{{TableName}}"
    }
   ]
  }
 ]
}