{
 "title": "CloudWatch - EBS Volume",
 "description": "Visualize AWS EBS metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": { "query": "label_values(__aws_region)" } },
   { "name": "volumeid", "label": "VolumeId", "query": { "query": "label_values(VolumeId)" } }
  ]
 },
 "panels": [
  {
   "title": "Idle Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "expr": "avg(amazonaws_com_AWS_EBS_VolumeIdleTime_sum{__aws_region=\"$region\",VolumeId=~\"$volumeid\",VolumeId!=\"\"}) by (VolumeId)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{VolumeId}}",
     "metricName": "VolumeTotalReadTime",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeTotalWriteTime",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeIdleTime",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Volume Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "expr": "amazonaws_com_AWS_EBS_VolumeQueueLength_sum{__aws_region=\"$region\",VolumeId=~\"$volumeid\",VolumeId!=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{VolumeId}}",
     "metricName": "VolumeQueueLength",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Volume Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "expr": "avg(amazonaws_com_AWS_EBS_VolumeIdleTime_sum{__aws_region=\"$region\",VolumeId=~\"$volumeid\",VolumeId!=\"\"}) by (VolumeId)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{VolumeId}}",
     "metricName": "VolumeTotalReadTime",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeTotalWriteTime",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeIdleTime",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Volume Read/Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "expr": "avg(amazonaws_com_AWS_EBS_VolumeReadBytes_sum{__aws_region=\"$region\",VolumeId=~\"$volumeid\",VolumeId!=\"\"}) by (VolumeId)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read: {{VolumeId}}",
     "metricName": "VolumeThroughputPercentage",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "expr": "avg(amazonaws_com_AWS_EBS_VolumeWriteBytes_sum{__aws_region=\"$region\",VolumeId=~\"$volumeid\",VolumeId!=\"\"}) by (VolumeId)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write: {{VolumeId}}",
     "metricName": "VolumeConsumedReadWriteOps",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Volume Read/Write Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "expr": "avg(amazonaws_com_AWS_EBS_VolumeReadOps_sum{__aws_region=\"$region\",VolumeId=~\"$volumeid\",VolumeId!=\"\"}) by (VolumeId)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read: {{VolumeId}}",
     "metricName": "VolumeThroughputPercentage",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "expr": "avg(amazonaws_com_AWS_EBS_VolumeWriteOps_sum{__aws_region=\"$region\",VolumeId=~\"$volumeid\",VolumeId!=\"\"}) by (VolumeId)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write: {{VolumeId}}",
     "metricName": "VolumeConsumedReadWriteOps",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Volume Read/Write Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "expr": "avg(amazonaws_com_AWS_EBS_VolumeTotalReadTime_sum{__aws_region=\"$region\",VolumeId=~\"$volumeid\",VolumeId!=\"\"}) by (VolumeId)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read: {{VolumeId}}",
     "metricName": "VolumeThroughputPercentage",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "expr": "avg(amazonaws_com_AWS_EBS_VolumeTotalWriteTime_sum{__aws_region=\"$region\",VolumeId=~\"$volumeid\",VolumeId!=\"\"}) by (VolumeId)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write: {{VolumeId}}",
     "metricName": "VolumeConsumedReadWriteOps",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}