{
 "title": "CloudWatch - EC2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "InstanceId", "label": "Instance ID", "query": { "query": "label_values(InstanceId)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count(amazonaws_com_AWS_EC2_CPUUtilization{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId))",
     "legendFormat": "Instances"
    },
    {
     "expr": "count(count(amazonaws_com_AWS_EC2_CPUUtilization{quantile=\"1\"}) by (AutoScalingGroupName))",
     "legendFormat": "Auto Scale Groups"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EC2_CPUUtilization{InstanceId=~\"$InstanceId\",quantile=\"1\"})",
     "legendFormat": "Avg CPU Utilization"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EC2_DiskReadBytes{InstanceId=~\"$InstanceId\",quantile=\"1\"})",
     "legendFormat": "Avg Read Bytes"
    },
    {
     "expr": "sum(amazonaws_com_AWS_EC2_DiskWriteBytes{InstanceId=~\"$InstanceId\",quantile=\"1\"})",
     "legendFormat": "Avg Write Bytes"
    },
    {
     "expr": "sum(amazonaws_com_AWS_EC2_NetworkIn{InstanceId=~\"$InstanceId\",quantile=\"1\"}) ",
     "legendFormat": "Avg Network In Bytes"
    },
    {
     "expr": "sum(amazonaws_com_AWS_EC2_NetworkOut{InstanceId=~\"$InstanceId\",quantile=\"1\"}) ",
     "legendFormat": "Avg Network Out Bytes"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Average CPU utilization percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EC2_CPUUtilization{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
     "legendFormat": "{{InstanceId}}"
    }
   ]
  },
  {
   "title": "CPU Credit Usage",
   "type": "timeseries",
   "description": "The number of CPU credits spent by the instance for CPU utilization. One CPU credit equals one vCPU running at 100% utilization for one minute or an equivalent combination of vCPUs, utilization, and time (for example, one vCPU running at 50% utilization for two minutes or two vCPUs running at 25% utilization for two minutes).\n\nCPU credit metrics are available at a 5-minute frequency only. If you specify a period greater than five minutes, use the Sum statistic instead of the Average statistic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EC2_CPUCreditUsage{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId) or vector(0)",
     "legendFormat": "{{InstanceId}}"
    }
   ]
  },
  {
   "title": "CPU Credit Balance",
   "type": "timeseries",
   "description": "The number of earned CPU credits that an instance has accrued since it was launched or started. For T2 Standard, the CPUCreditBalance also includes the number of launch credits that have been accrued.\n\nCredits are accrued in the credit balance after they are earned, and removed from the credit balance when they are spent. The credit balance has a maximum limit, determined by the instance size. After the limit is reached, any new credits that are earned are discarded. For T2 Standard, launch credits do not count towards the limit.\n\nThe credits in the CPUCreditBalance are available for the instance to spend to burst beyond its baseline CPU utilization.\n\nWhen an instance is running, credits in the CPUCreditBalance do not expire. When a T3 or T3a instance stops, the CPUCreditBalance value persists for seven days. Thereafter, all accrued credits are lost. When a T2 instance stops, the CPUCreditBalance value does not persist, and all accrued credits are lost.\n\nCPU credit metrics are available at a 5-minute frequency only.\n\nUnits: Credits (vCPU-minutes)\nCPU credit metrics are available at a 5-minute frequency only. If you specify a period greater than five minutes, use the Sum statistic instead of the Average statistic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EC2_CPUCreditBalance{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId) or vector(0)",
     "legendFormat": "{{InstanceId}}"
    }
   ]
  },
  {
   "title": "CPU Surplus Credit Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EC2_CPUSurplusCreditBalance{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId) or vector(0)",
     "legendFormat": "{{InstanceId}}"
    }
   ]
  },
  {
   "title": "CPU Surplus Credits Charged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EC2_CPUSurplusCreditsCharged{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId) or vector(0)",
     "legendFormat": "{{InstanceId}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Reads Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_EC2_DiskReadBytes{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "Disk Write Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_EC2_DiskWriteBytes{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "Disk Read Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_EC2_DiskReadOps{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "Disk Write Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_EC2_DiskWriteOps{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "EBS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "EBS Byte Balance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(amazonaws_com_AWS_EC2_EBSByteBalance_{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "EBS IO Balance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(amazonaws_com_AWS_EC2_EBSIOBalance_{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "EBS Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(amazonaws_com_AWS_EC2_EBSReadBytes{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "EBS Write Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(amazonaws_com_AWS_EC2_EBSWriteBytes{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "EBS Read Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "avg(amazonaws_com_AWS_EC2_EBSReadOps{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "EBS Write Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "avg(amazonaws_com_AWS_EC2_EBSWriteOps{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_EC2_NetworkIn{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "Bytes Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_EC2_NetworkOut{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "Packets In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_EC2_NetworkPacketsIn{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "Packets Out by Group",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_EC2_NetworkPacketsOut{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metadata & Status ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metadata No Token",
     "type": "timeseries",
     "description": "The number of times the instance metadata service was successfully accessed using a method that does not use a token.\n\nThis metric is used to determine if there are any processes accessing instance metadata that are using Instance Metadata Service Version 1, which does not use a token. If all requests use token-backed sessions, i.e., Instance Metadata Service Version 2, the value is 0.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_EC2_MetadataNoToken{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "Status Check Failed",
     "type": "timeseries",
     "description": "Reports whether the instance has passed both the instance status check and the system status check in the last minute.\n\nThis metric can be either 0 (passed) or 1 (failed).\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_EC2_StatusCheckFailed{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "Status Check Failed - Instance",
     "type": "timeseries",
     "description": "Reports whether the instance has passed the instance status check in the last minute.\n\nThis metric can be either 0 (passed) or 1 (failed).\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_EC2_StatusCheckFailed_Instance{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    },
    {
     "title": "Status Check Failed - System",
     "type": "timeseries",
     "description": "Reports whether the instance has passed the system status check in the last minute.\nThis metric can be either 0 (passed) or 1 (failed).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_EC2_StatusCheckFailed_System{InstanceId=~\"$InstanceId\",quantile=\"1\"}) by (InstanceId)",
       "legendFormat": "{{InstanceId}}"
      }
     ]
    }
   ]
  }
 ]
}