{
 "title": "CloudWatch - EC2 by InstanceId",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AutoScalingGroupName",
    "query": {
     "query": "label_values(AutoScalingGroupName)"
    }
   },
   { "name": "InstanceId", "query": { "query": "label_values(InstanceId)" } }
  ]
 },
 "panels": [
  {
   "title": "95% CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.95,amazonaws_com_AWS_EC2_CPUUtilization{InstanceId=~\"$InstanceId\"}) by (InstanceId)",
     "legendFormat": "{{InstanceId}}"
    }
   ]
  },
  {
   "title": "CPU Credit Balance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EC2_CPUCreditBalance{InstanceId=~\"$InstanceId\"}) by (InstanceId)",
     "legendFormat": "{{InstanceId}}"
    }
   ]
  },
  {
   "title": "Average CPU Utilization Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EC2_CPUUtilization{InstanceId=~\"$InstanceId\"})",
     "legendFormat": "$InstanceId"
    }
   ]
  },
  {
   "title": "Status Check Failed Count by InstanceId",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_EC2_StatusCheckFailed_System_count{InstanceId=~\"$InstanceId\"}",
     "legendFormat": "{{InstanceId}}"
    }
   ]
  },
  {
   "title": "Average Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EC2_NetworkIn{InstanceId=~\"$InstanceId\"})",
     "legendFormat": "$InstanceId"
    }
   ]
  },
  {
   "title": "Average Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EC2_NetworkOut{InstanceId=~\"$InstanceId\"})",
     "legendFormat": "$InstanceId"
    }
   ]
  },
  {
   "title": "Average Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EC2_NetworkIn{InstanceId=~\"$InstanceId\"})",
     "legendFormat": "$InstanceId"
    }
   ]
  },
  {
   "title": "Average Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EC2_NetworkOut{InstanceId=~\"$InstanceId\"})",
     "legendFormat": "$InstanceId"
    }
   ]
  },
  {
   "title": "Average Disk Write Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EC2_EBSWriteOps{InstanceId=~\"$InstanceId\"})",
     "legendFormat": "$InstanceId"
    }
   ]
  },
  {
   "title": "Average Disk Read Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EC2_EBSReadOps{InstanceId=~\"$InstanceId\"})",
     "legendFormat": "$InstanceId"
    }
   ]
  }
 ]
}