{
 "title": "CloudWatch FSx Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "FileSystemId", "label": "Filesystem ID", "query": { "query": "label_values(FileSystemId)" } }
  ]
 },
 "panels": [
  {
   "title": "Filesystems",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count(amazonaws_com_AWS_FSx_DataReadBytes{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId))"
    }
   ]
  },
  {
   "title": "Read operations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_FSx_DataReadOperations{FileSystemId=~\"$FileSystemId\"})"
    }
   ]
  },
  {
   "title": "FSx Meta Operations by Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_FSx_MetadataOperations{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId)",
     "legendFormat": "{{FileSystemId}}"
    }
   ]
  },
  {
   "title": "Bytes read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_FSx_DataReadBytes{FileSystemId=~\"$FileSystemId\"})"
    }
   ]
  },
  {
   "title": "Bytes written",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_FSx_DataWriteBytes{FileSystemId=~\"$FileSystemId\"})"
    }
   ]
  },
  {
   "title": "Free capacity min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "min(amazonaws_com_AWS_FSx_FreeDataStorageCapacity{FileSystemId=~\"$FileSystemId\"})"
    }
   ]
  },
  {
   "title": "Write operations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_FSx_DataWriteBytes{FileSystemId=~\"$FileSystemId\"})"
    }
   ]
  },
  {
   "title": "Metadata operations max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(amazonaws_com_AWS_FSx_MetadataOperations{FileSystemId=~\"$FileSystemId\"})"
    }
   ]
  },
  {
   "title": "FSx Data Reads Operations by Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_FSx_DataReadOperations{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId)",
     "legendFormat": "{{FileSystemId}}"
    }
   ]
  },
  {
   "title": "FSx Data Write Operations by Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_FSx_DataWriteOperations{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId)",
     "legendFormat": "{{FileSystemId}}"
    }
   ]
  },
  {
   "title": "FSx Data Read bytes by Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_FSx_DataReadBytes{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId)",
     "legendFormat": "{{FileSystemId}}"
    }
   ]
  },
  {
   "title": "FSx Data Write bytes by Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_FSx_DataWriteBytes{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId)",
     "legendFormat": "{{FileSystemId}}"
    }
   ]
  },
  {
   "title": "FSx Free Capacity by Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_FSx_FreeDataStorageCapacity{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId)",
     "legendFormat": "{{FileSystemId}}"
    }
   ]
  }
 ]
}