{
 "title": "CloudWatch - Kinesis Firehose",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "firehose_stream",
    "query": {
     "query": "label_values(DeliveryStreamName)"
    }
   },
   { "name": "aws_account_id", "query": { "query": "label_values(account_id)" } },
   { "name": "coralogix_account_id", "query": { "query": "label_values(cx_tenant_id)" } },
   { "name": "aws_region", "query": { "query": "label_values(__aws_region)" } }
  ]
 },
 "panels": [
  {
   "title": "Delivery to Http Endpoint ProcessedBytes: Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_Firehose_DeliveryToHttpEndpoint_ProcessedBytes_sum{DeliveryStreamName=~\"$firehose_stream\",account_id=~\"$aws_account_id\",cx_tenant_id=~\"$coralogix_account_id\",__aws_region=~\"$aws_region\"}) by (DeliveryStreamName)",
     "legendFormat": "{{DeliveryStreamName}}"
    }
   ]
  },
  {
   "title": "Delivery to Http Endpoint Processed Records Count: Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_Firehose_DeliveryToHttpEndpoint_ProcessedRecords_count{DeliveryStreamName=~\"$firehose_stream\",account_id=~\"$aws_account_id\",cx_tenant_id=~\"$coralogix_account_id\",__aws_region=~\"$aws_region\"}) by (DeliveryStreamName)",
     "legendFormat": "{{DeliveryStreamName}}"
    }
   ]
  },
  {
   "title": "Delivery to Http End Point Success: Sum",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_Firehose_KMSKeyAccessDenied_count{DeliveryStreamName=~\"$firehose_stream\",account_id=~\"$aws_account_id\",cx_tenant_id=~\"$coralogix_account_id\",__aws_region=~\"$aws_region\"}) by (DeliveryStreamName)",
     "legendFormat": "{{DeliveryStreamName}}"
    }
   ]
  },
  {
   "title": "Incoming Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_Firehose_IncomingRecords_count{DeliveryStreamName=~\"$firehose_stream\",account_id=~\"$aws_account_id\",cx_tenant_id=~\"$coralogix_account_id\",__aws_region=~\"$aws_region\"}) by (DeliveryStreamName)",
     "legendFormat": "{{DeliveryStreamName}}"
    },
    {
     "expr": "avg_over_time(amazonaws_com_AWS_Firehose_RecordsPerSecondLimit_sum{DeliveryStreamName=~\"$firehose_stream\", __meta_account_id=~\"$aws_account_id\", cx_tenant_id=~\"$coralogix_account_id\"}[10m])",
     "legendFormat": "records per second limit"
    }
   ]
  },
  {
   "title": "Incoming Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_Firehose_IncomingBytes_sum{DeliveryStreamName=~\"$firehose_stream\",account_id=~\"$aws_account_id\",cx_tenant_id=~\"$coralogix_account_id\",__aws_region=~\"$aws_region\"}) by (DeliveryStreamName)",
     "legendFormat": "{{DeliveryStreamName}}"
    },
    {
     "expr": "avg_over_time(amazonaws_com_AWS_Firehose_BytesPerSecondLimit_sum{DeliveryStreamName=~\"$firehose_stream\", __meta_account_id=~\"$aws_account_id\", cx_tenant_id=~\"$coralogix_account_id\"}[10m])",
     "legendFormat": "Bytes Per Second Limit"
    }
   ]
  },
  {
   "title": "Failed/Retried Processed Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Rec" } },
   "targets": [
    {
     "expr": "(sum without (MetricName)(amazonaws_com_AWS_Firehose_DeliveryToHttpEndpoint_ProcessedRecords_sum{DeliveryStreamName=~\"$firehose_stream\",account_id=~\"$aws_account_id\",cx_tenant_id=~\"$coralogix_account_id\",__aws_region=~\"$aws_region\"}))-(sum without (MetricName)(amazonaws_com_AWS_Firehose_DeliveryToHttpEndpoint_Records_sum{DeliveryStreamName=~\"$firehose_stream\",account_id=~\"$aws_account_id\",cx_tenant_id=~\"$coralogix_account_id\",__aws_region=~\"$aws_region\"}))",
     "legendFormat": "{{DeliveryStreamName}}"
    }
   ]
  },
  {
   "title": "Throttled Records VS Put Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_Firehose_IncomingPutRequests_sum{DeliveryStreamName=~\"$firehose_stream\",account_id=~\"$aws_account_id\",cx_tenant_id=~\"$coralogix_account_id\",__aws_region=~\"$aws_region\"}) by (DeliveryStreamName)",
     "legendFormat": "Put Records - {{ DeliveryStreamName }}"
    },
    {
     "expr": "sum(amazonaws_com_AWS_Firehose_ThrottledRecords_sum{DeliveryStreamName=~\"$firehose_stream\",account_id=~\"$aws_account_id\",cx_tenant_id=~\"$coralogix_account_id\",__aws_region=~\"$aws_region\"}) by (DeliveryStreamName)",
     "legendFormat": "Throttled - {{ DeliveryStreamName }}"
    }
   ]
  }
 ]
}