{
 "title": "AWS Network Load Balancer",
 "tags": [ "CloudWatch" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(amazonaws_com_AWS_NetworkELB_HealthyHostCount, __aws_region)"
    }
   },
   {
    "name": "loadbalancer",
    "label": "Load Balancer",
    "query": {
     "query": "label_values(amazonaws_com_AWS_NetworkELB_HealthyHostCount, LoadBalancer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy Host Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(amazonaws_com_AWS_NetworkELB_HealthyHostCount_sum{__aws_region=~\"$region\",LoadBalancer=~\"$loadbalancer\"}) by (LoadBalancer)",
     "legendFormat": "Healthy - {{LoadBalancer}}"
    },
    {
     "expr": "count(amazonaws_com_AWS_NetworkELB_UnHealthyHostCount_sum{__aws_region=~\"$region\",LoadBalancer=\"$loadbalancer\"})",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Unhealthy Host Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(amazonaws_com_AWS_NetworkELB_UnHealthyHostCount_sum{__aws_region=~\"$region\",LoadBalancer=~\"$loadbalancer\"}) by (LoadBalancer)",
     "legendFormat": "Unhealthy - {{LoadBalancer}}"
    }
   ]
  },
  {
   "title": "Active Flow and TCP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(amazonaws_com_AWS_NetworkELB_ActiveFlowCount_sum{__aws_region=~\"$region\", LoadBalancer=~\"$loadbalancer\"}) by (LoadBalancer)",
     "legendFormat": "{{LoadBalancer}}"
    }
   ]
  },
  {
   "title": "New Flow and New Flow TCP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count(amazonaws_com_AWS_NetworkELB_NewFlowCount_sum{__aws_region=~\"$region\", LoadBalancer=~\"$loadbalancer\"}) by (LoadBalancer)",
     "legendFormat": "{{LoadBalancer}}"
    },
    {
     "expr": "count(amazonaws_com_AWS_NetworkELB_NewFlowCount_TCP_sum{__aws_region=~\"$region\", LoadBalancer=~\"$loadbalancer\"}) by (LoadBalancer)",
     "legendFormat": "TCP: {{LoadBalancer}}"
    }
   ]
  },
  {
   "title": "Processed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_NetworkELB_ProcessedBytes{__aws_region=~\"$region\", LoadBalancer=~\"$loadbalancer\"}) by (LoadBalancer)",
     "legendFormat": "{{LoadBalancer}}"
    }
   ]
  },
  {
   "title": "Consumed LCU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_NetworkELB_ConsumedLCUs{__aws_region=~\"$region\", LoadBalancer=~\"$loadbalancer\"}) by (LoadBalancer)",
     "legendFormat": "{{LoadBalancer}}"
    }
   ]
  },
  {
   "title": "Peak Packets per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_NetworkELB_PeakPacketsPerSecond{__aws_region=~\"$region\", LoadBalancer=~\"$loadbalancer\"}) by (LoadBalancer)",
     "legendFormat": "{{LoadBalancer}}"
    }
   ]
  },
  {
   "title": "TCP ELB Reset Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_NetworkELB_TCP_ELB_Reset_Count{__aws_region=~\"$region\", LoadBalancer=~\"$loadbalancer\"}) by (LoadBalancer)",
     "legendFormat": "{{LoadBalancer}}"
    }
   ]
  },
  {
   "title": "TCP Client Reset Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_NetworkELB_TCP_Client_Reset_Count{__aws_region=~\"$region\", LoadBalancer=~\"$loadbalancer\"}) by (LoadBalancer)",
     "legendFormat": "{{LoadBalancer}}"
    }
   ]
  },
  {
   "title": "TCP Target Reset Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_NetworkELB_TCP_Target_Reset_Count{__aws_region=~\"$region\", LoadBalancer=~\"$loadbalancer\"}) by (LoadBalancer)",
     "legendFormat": "{{LoadBalancer}}"
    }
   ]
  },
  {
   "title": "Port Allocation Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_NetworkELB_PortAllocationErrorCount{__aws_region=~\"$region\", LoadBalancer=~\"$loadbalancer\"}) by (LoadBalancer)",
     "legendFormat": "{{LoadBalancer}}"
    }
   ]
  }
 ]
}