{
 "title": "CloudWatch - RDS DB Instance",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DBInstanceIdentifier",
    "label": "DB Instance Identifier",
    "query": {
     "query": "label_values(DBInstanceIdentifier)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DB CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_CPUUtilization{DBInstanceIdentifier=~\"$DBInstanceIdentifier\",DBInstanceIdentifier!=\"\"}) by (DBInstanceIdentifier)",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_Deadlocks_sum{DBInstanceIdentifier=~\"$DBInstanceIdentifier\",DBInstanceIdentifier!=\"\"}) by (DBInstanceIdentifier)",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Connections (Max 3000)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_DatabaseConnections{DBInstanceIdentifier=~\"$DBInstanceIdentifier\",DBInstanceIdentifier!=\"\"}) by (DBInstanceIdentifier)",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Row Lock Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_RowLockTime{DBInstanceIdentifier=~\"$DBInstanceIdentifier\",DBInstanceIdentifier!=\"\"}) by (DBInstanceIdentifier)",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "DB CPU Utilization % (All Role)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_CPUUtilization{DBClusterIdentifier!=\"\",Role!=\"\"}) by (Role,DBClusterIdentifier) ",
     "legendFormat": "{{Role}}>>{{DBClusterIdentifier}}"
    }
   ]
  }
 ]
}