{
 "title": "CloudWatch - RDS",
 "description": "This dashboard provides an overview of the standard AWS RDS metrics (Via FireHose from CloudWatch), so you can track key metrics around database connections, resource utilization, and replication status.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "AWS Region", "query": { "query": "label_values(__aws_region)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(amazonaws_com_AWS_RDS_CPUUtilization{__aws_region=~\"$region\"},DBInstanceIdentifier)"
    }
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": {
     "query": "label_values(amazonaws_com_AWS_RDS_CPUUtilization{__aws_region=~\"$region\"},quantile)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count(amazonaws_com_AWS_RDS_CPUUtilization{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}>0) by (__aws_region))",
     "legendFormat": "AWS Regions"
    },
    {
     "expr": "count(count(amazonaws_com_AWS_RDS_CPUUtilization{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}>0) by (DBInstanceIdentifier))",
     "legendFormat": "RDS Instances"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_CPUUtilization{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"})"
    }
   ]
  },
  {
   "title": "Read OPS/sec",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_ReadIOPS{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"})"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(amazonaws_com_AWS_RDS_ReadLatency{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"})",
     "legendFormat": "Read Latency"
    },
    {
     "expr": "max(amazonaws_com_AWS_RDS_WriteLatency{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"})",
     "legendFormat": "Write Latency"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_ReplicaLag{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"})",
     "legendFormat": "Replica Lag"
    },
    {
     "expr": "avg(amazonaws_com_AWS_RDS_CheckpointLag{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"})",
     "legendFormat": "Checkpoint Lag"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_NetworkTransmitThroughput{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"})",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "avg(amazonaws_com_AWS_RDS_NetworkReceiveThroughput{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"})",
     "legendFormat": "Network  Receive"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(amazonaws_com_AWS_RDS_FreeStorageSpace{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"})"
    }
   ]
  },
  { "title": "CPU & Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Average CPU Utilization by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_CPUUtilization{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier)",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Max Database Connections by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max(amazonaws_com_AWS_RDS_DatabaseConnections{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}>0) by (DBInstanceIdentifier) ",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Max Database Connections by Instance",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_RDS_DatabaseConnections{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}>0) by (DBInstanceIdentifier) ",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Read Latency by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_ReadLatency{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier)  ",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Write Latency by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_WriteLatency{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier)",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Read IOPS by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_ReadIOPS{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier) ",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Write IOPS by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_WriteIOPS{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier)",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Free Storage Space by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "min(amazonaws_com_AWS_RDS_FreeStorageSpace{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier)",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Used Swap Space by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_SwapUsage{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier)",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Disk Queue Depth by Instance",
   "type": "timeseries",
   "description": "The number of outstanding I/Os (read/write requests) waiting to access the disk.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_DiskQueueDepth{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier)",
     "legendFormat": "{{DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "EBS Bytes/IO Balance",
   "type": "timeseries",
   "description": "The percentage of throughput and I/O credits remaining in the burst bucket of your RDS database. This metric is available for basic monitoring only.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_RDS_EBSByteBalance_{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier)",
     "legendFormat": "{{DBInstanceIdentifier}} - Bytes"
    },
    {
     "expr": "avg(amazonaws_com_AWS_RDS_EBSIOBalance_{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier)",
     "legendFormat": "{{DBInstanceIdentifier}} - IO"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Transmit Throughput by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg(amazonaws_com_AWS_RDS_NetworkTransmitThroughput{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier)",
       "legendFormat": "{{DBInstanceIdentifier}} - Bytes"
      }
     ]
    },
    {
     "title": "Network Receive Throughput by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg(amazonaws_com_AWS_RDS_NetworkReceiveThroughput{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier)",
       "legendFormat": "{{DBInstanceIdentifier}} - Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Lag Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Replica Lag by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(amazonaws_com_AWS_RDS_ReplicaLag{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier)",
       "legendFormat": "{{DBInstanceIdentifier}}"
      }
     ]
    },
    {
     "title": "Average Checkpoint Lag by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(amazonaws_com_AWS_RDS_CheckpointLag{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier)",
       "legendFormat": "{{DBInstanceIdentifier}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Sessions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_RDS_DBLoad{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier) ",
       "legendFormat": "{{DBInstanceIdentifier}}"
      }
     ]
    },
    {
     "title": "Active Sessions in \"CPU wait\" Status",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_RDS_DBLoadCPU{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier) ",
       "legendFormat": "{{DBInstanceIdentifier}}"
      }
     ]
    },
    {
     "title": "Active Sessions Not in \"CPU wait\" Status",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_RDS_DBLoadNonCPU{DBInstanceIdentifier=~\"$instance\",__aws_region=~\"$region\",quantile=\"$quantile\"}) by (DBInstanceIdentifier) ",
       "legendFormat": "{{DBInstanceIdentifier}}"
      }
     ]
    }
   ]
  }
 ]
}