{
 "title": "AWS SQS",
 "description": "Visualize AWS SQS metrics",
 "tags": [ "CloudWatch" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(amazonaws_com_AWS_SQS_NumberOfMessagesReceived_count, __aws_region)"
    }
   },
   {
    "name": "queue",
    "label": "Queue name",
    "query": {
     "query": "label_values(amazonaws_com_AWS_SQS_NumberOfMessagesReceived_count, QueueName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum(amazonaws_com_AWS_SQS_NumberOfMessagesReceived_count{__aws_region=~\"$region\", QueueName=~\"$queue\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Messages Received",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum(amazonaws_com_AWS_SQS_NumberOfMessagesSent_count{__aws_region=~\"$region\", QueueName=~\"$queue\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Messages Sent",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum(amazonaws_com_AWS_SQS_NumberOfMessagesDeleted_count{__aws_region=~\"$region\", QueueName=~\"$queue\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Messages Deleted",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Messages Received by Queue",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum(amazonaws_com_AWS_SQS_NumberOfMessagesReceived_count{__aws_region=~\"$region\", QueueName=~\"$queue\"}) by (QueueName)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{QueueName}}",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Messages Sent by Queue",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum(amazonaws_com_AWS_SQS_NumberOfMessagesSent_count{__aws_region=~\"$region\", QueueName=~\"$queue\"}) by (QueueName)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{QueueName}}",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Messages Deleted by Queue",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum(amazonaws_com_AWS_SQS_NumberOfMessagesDeleted_count{__aws_region=~\"$region\", QueueName=~\"$queue\"}) by (QueueName)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{QueueName}}",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ApproximateNumberOfMessages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum(amazonaws_com_AWS_SQS_ApproximateNumberOfMessagesVisible_count{__aws_region=~\"$region\",QueueName=\"$queue\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Messages Visible",
     "metricName": "ApproximateNumberOfMessagesNotVisible",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum(amazonaws_com_AWS_SQS_ApproximateNumberOfMessagesNotVisible_count{__aws_region=~\"$region\",QueueName=\"$queue\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Messages Not Visible",
     "metricName": "ApproximateNumberOfMessagesDelayed",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum(amazonaws_com_AWS_SQS_ApproximateNumberOfMessagesDelayed_count{__aws_region=~\"$region\", QueueName=~\"$queue\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Messages Delayed",
     "metricName": "ApproximateNumberOfMessagesNotVisible",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NumberOfEmptyReceives",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum(amazonaws_com_AWS_SQS_NumberOfEmptyReceives_count{__aws_region=~\"$region\", QueueName=~\"$queue\"}) by (QueueName)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{QueueName}}",
     "metricName": "NumberOfEmptyReceives",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ApproximateAgeOfOldestMessage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "avg(amazonaws_com_AWS_SQS_ApproximateAgeOfOldestMessage{__aws_region=~\"$region\", QueueName=~\"$queue\"}) by (QueueName)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{QueueName}}",
     "metricName": "ApproximateAgeOfOldestMessage",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SentMessageSize",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum(amazonaws_com_AWS_SQS_SentMessageSize{__aws_region=~\"$region\",QueueName=~\"$queue\"}) by (QueueName)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{QueueName}}",
     "metricName": "SentMessageSize",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}