{
 "title": "Elasticache Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cache_cluster_id", "label": "Cache Cluster Id", "query": { "query": "label_values(cache_cluster_id)" } },
   { "name": "cache_node_id", "label": "Cache Node Id", "query": { "query": "label_values(cache_node_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Cluster Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cloudwatch_aws_elasti_cache_is_master_sum{cache_cluster_id!=\"\",cache_node_id=\"\"})"
    }
   ]
  },
  {
   "title": "Cache Miss %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(cloudwatch_aws_elasti_cache_cache_misses_sum{})/(sum(cloudwatch_aws_elasti_cache_cache_hits_sum{})+sum(cloudwatch_aws_elasti_cache_cache_misses_sum{})))*100"
    }
   ]
  },
  {
   "title": "Current Connection",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_elasti_cache_curr_connections_sum{cache_cluster_id!=\"\",cache_node_id=\"\",cache_cluster_id=~\"$cache_cluster_id\"}) by (cache_cluster_id)",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Network Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_elasti_cache_network_bytes_out_sum{cache_cluster_id!=\"\",cache_node_id=\"\",cache_cluster_id=~\"$cache_cluster_id\"}) by (cache_cluster_id)",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Cache Hits vs Misses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_elasti_cache_cache_hits_sum{})",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "sum(cloudwatch_aws_elasti_cache_cache_misses_sum{})",
     "legendFormat": "Cache Misses"
    }
   ]
  },
  {
   "title": "Cache Read vs Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_elasti_cache_get_type_cmds_sum{cache_cluster_id!=\"\",cache_node_id=\"\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(cloudwatch_aws_elasti_cache_set_type_cmds_sum{cache_cluster_id!=\"\",cache_node_id=\"\"})",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Items",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_elasti_cache_curr_items_average{cache_cluster_id!=\"\",cache_node_id=\"\",cache_cluster_id=~\"$cache_cluster_id\"}) by (cache_cluster_id)",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Total bytes allocated by Redis",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_elasti_cache_bytes_used_for_cache_sum{cache_cluster_id!=\"\",cache_node_id=\"\",cache_cluster_id=~\"$cache_cluster_id\"}) by (cache_cluster_id)",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_elasti_cache_replication_lag_average{cache_cluster_id!=\"\",cache_node_id=\"\",cache_cluster_id=~\"$cache_cluster_id\"}) by (cache_cluster_id)",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_elasti_cache_database_memory_usage_percentage_average{cache_node_id!=\"\",cache_node_id=~\"$cache_node_id\"}) by (cache_node_id)",
     "legendFormat": "Node: {{cache_node_id}}"
    }
   ]
  },
  {
   "title": "CPU Utilization by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_elasti_cache_engine_cpu_utilization_average{cache_cluster_id!=\"\",cache_node_id=\"\",cache_cluster_id=~\"$cache_cluster_id\"}) by (cache_cluster_id)",
     "legendFormat": "Server: {{cache_cluster_id}}"
    },
    {
     "expr": "avg(cloudwatch_aws_elasti_cache_cpu_utilization_average{cache_cluster_id!=\"\",cache_node_id=\"\",cache_cluster_id=~\"$cache_cluster_id\"}) by (cache_cluster_id)",
     "legendFormat": "Redis: {{cache_cluster_id}}"
    }
   ]
  }
 ]
}