{
 "title": "ElastiCache Dashboard (Metric Stream)",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "CacheClusterId", "label": "Cache Cluster Id", "query": { "query": "label_values(CacheClusterId)" } },
   { "name": "CacheNodeId", "label": "Cache Node Id", "query": { "query": "label_values(CacheNodeId)" } }
  ]
 },
 "panels": [
  {
   "title": "Cluster Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(amazonaws_com_AWS_ElastiCache_IsMaster_sum{CacheClusterId!=\"\",CacheNodeId=\"\"})"
    }
   ]
  },
  {
   "title": "Cache Miss %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(amazonaws_com_AWS_ElastiCache_CacheMisses_sum{})/(sum(amazonaws_com_AWS_ElastiCache_CacheHits_sum{})+sum(amazonaws_com_AWS_ElastiCache_CacheMisses_sum{})))*100"
    }
   ]
  },
  {
   "title": "Current Connection",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_ElastiCache_CurrConnections_sum{CacheClusterId!=\"\",CacheNodeId=\"\",CacheClusterId=~\"$CacheClusterId\"}) by (CacheClusterId)",
     "legendFormat": "{{CacheClusterId}}"
    }
   ]
  },
  {
   "title": "Network Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_ElastiCache_NetworkBytesOut_sum{CacheClusterId!=\"\",CacheClusterId=~\"$CacheClusterId\",CacheNodeId=\"\"}) by (CacheClusterId)",
     "legendFormat": "{{CacheClusterId}}"
    }
   ]
  },
  {
   "title": "Cache Hits vs Misses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_ElastiCache_CacheHits_sum{})",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "sum(amazonaws_com_AWS_ElastiCache_CacheMisses_sum{})",
     "legendFormat": "Cache Misses"
    }
   ]
  },
  {
   "title": "Cache Read vs Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_ElastiCache_GetTypeCmds_sum{CacheClusterId!=\"\",CacheNodeId=\"\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(amazonaws_com_AWS_ElastiCache_SetTypeCmds_sum{CacheClusterId!=\"\",CacheNodeId=\"\"})",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Items",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_ElastiCache_CurrItems_sum{CacheClusterId!=\"\",CacheNodeId=\"\",CacheClusterId=~\"$CacheClusterId\"}) by (CacheClusterId)",
     "legendFormat": "{{CacheClusterId}}"
    }
   ]
  },
  {
   "title": "Total bytes allocated by Redis",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_ElastiCache_BytesUsedForCache_sum{CacheClusterId!=\"\",CacheNodeId=\"\",CacheClusterId=~\"$CacheClusterId\"}) by (CacheClusterId)",
     "legendFormat": "{{CacheClusterId}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_ElastiCache_ReplicationLag{CacheClusterId!=\"\",CacheNodeId=\"\",CacheClusterId=~\"$CacheClusterId\"}) by (CacheClusterId)",
     "legendFormat": "{{CacheClusterId}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_ElastiCache_DatabaseMemoryUsagePercentage{CacheNodeId!=\"\",CacheNodeId=~\"$CacheNodeId\"}) by (CacheNodeId)",
     "legendFormat": "Node: {{CacheNodeId}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Cluster)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_ElastiCache_DatabaseMemoryUsagePercentage{CacheClusterId!=\"\",CacheClusterId=~\"$CacheClusterId\"}) by (CacheClusterId)",
     "legendFormat": "Cluster: {{CacheClusterId}}"
    }
   ]
  },
  {
   "title": "CPU Utilization by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_ElastiCache_EngineCPUUtilization{CacheNodeId!=\"\",CacheNodeId=~\"$CacheNodeId\"}) by (CacheNodeId)",
     "legendFormat": "Server: {{CacheNodeId}}"
    },
    {
     "expr": "avg(amazonaws_com_AWS_ElastiCache_CPUUtilization{CacheNodeId!=\"\",CacheNodeId=~\"$CacheNodeId\"}) by (CacheNodeId)",
     "legendFormat": "Redis: {{CacheNodeId}}"
    }
   ]
  },
  {
   "title": "CPU Utilization by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_ElastiCache_EngineCPUUtilization{CacheClusterId!=\"\",CacheNodeId=\"\",CacheClusterId=~\"$CacheClusterId\"}) by (CacheClusterId)",
     "legendFormat": "Server: {{CacheClusterId}}"
    },
    {
     "expr": "avg(amazonaws_com_AWS_ElastiCache_CPUUtilization{CacheClusterId!=\"\",CacheNodeId=\"\",CacheClusterId=~\"$CacheClusterId\"}) by (CacheClusterId)",
     "legendFormat": "Redis: {{CacheClusterId}}"
    }
   ]
  }
 ]
}