{
 "title": "Lambda Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(amazonaws_com_AWS_Lambda_Duration,__aws_region)"
    }
   },
   {
    "name": "function",
    "label": "Function",
    "query": {
     "query": "label_values(amazonaws_com_AWS_Lambda_Duration{__aws_region=~\"$region\"}, FunctionName)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count(amazonaws_com_AWS_Lambda_Duration{__aws_region=~\"$region\",FunctionName=~\"$function\"}) by (region)) ",
     "legendFormat": "Regions"
    },
    {
     "expr": "count(count(amazonaws_com_AWS_Lambda_Duration{__aws_region=~\"$region\",FunctionName=~\"$function\"}) by (FunctionName)) ",
     "legendFormat": "Functions"
    }
   ]
  },
  {
   "title": "Average Labmda Duration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_Lambda_Duration{__aws_region=~\"$region\",FunctionName=~\"$function\"})"
    }
   ]
  },
  {
   "title": "Max Labmda Errors",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_Lambda_Errors_sum{__aws_region=~\"$region\",FunctionName=~\"$function\"}>0) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_Lambda_Invocations_sum{__aws_region=~\"$region\",FunctionName=~\"$function\"}>0)",
     "legendFormat": "Lambda Invocations"
    },
    {
     "expr": "sum(amazonaws_com_AWS_Lambda_Errors_sum{__aws_region=~\"$region\",FunctionName=~\"$function\"}>0)",
     "legendFormat": "Lambda Errors"
    }
   ]
  },
  {
   "title": "Average Lambda Duration by Function",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_Lambda_Duration{__aws_region=~\"$region\",FunctionName=~\"$function\"}) by (FunctionName) > 0",
     "legendFormat": "{{FunctionName}}"
    }
   ]
  },
  {
   "title": "Lambda Invocations by Function",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_Lambda_Invocations_sum{__aws_region=~\"$region\",FunctionName=~\"$function\"}) by (FunctionName) > 0",
     "legendFormat": "{{FunctionName}}"
    }
   ]
  },
  {
   "title": "Lambda Errors by Function",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_Lambda_Errors_sum{__aws_region=~\"$region\",FunctionName=~\"$function\"}) by (FunctionName) >0 ",
     "legendFormat": "{{dimension_FunctionName}}"
    },
    { "expr": "vector(0)" }
   ]
  },
  {
   "title": "Lambda Throttles by Function",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_Lambda_Throttles_sum{__aws_region=~\"$region\",FunctionName=~\"$function\"}) by (FunctionName) >0",
     "legendFormat": "{{dimension_FunctionName}}"
    },
    { "expr": "vector(0)" }
   ]
  },
  {
   "title": "Lambda Concurrent Executions by Function",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(aws_lambda_concurrent_executions_sum{region=~\"$region\",dimension_FunctionName=~\"$function\"}) by (dimension_FunctionName) > 0",
     "legendFormat": "{{dimension_FunctionName}}"
    },
    { "expr": "vector(0)" }
   ]
  }
 ]
}