{
 "title": "CloudWatch EBS Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "VolumeId", "label": "Volume ID", "query": { "query": "label_values(VolumeId)" } }
  ]
 },
 "panels": [
  {
   "title": "EBS Volumes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count(amazonaws_com_AWS_EBS_BurstBalance{VolumeId=~\"$VolumeId\"}) by (VolumeId))"
    }
   ]
  },
  {
   "title": "Idle Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EBS_VolumeIdleTime{VolumeId=~\"$VolumeId\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "Max(amazonaws_com_AWS_EBS_VolumeIdleTime{VolumeId=~\"$VolumeId\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EBS_VolumeQueueLength{VolumeId=~\"$VolumeId\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "Max(amazonaws_com_AWS_EBS_VolumeQueueLength{VolumeId=~\"$VolumeId\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Read Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EBS_VolumeReadBytes{VolumeId=~\"$VolumeId\"})",
     "legendFormat": "Read Size"
    }
   ]
  },
  {
   "title": "Read Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EBS_VolumeReadOps{VolumeId=~\"$VolumeId\"})",
     "legendFormat": "Read Operations"
    }
   ]
  },
  {
   "title": "Read Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EBS_VolumeTotalReadTime_sum{VolumeId=~\"$VolumeId\"}) ",
     "legendFormat": "Read Time"
    }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EBS_VolumeWriteBytes{VolumeId=~\"$VolumeId\"})",
     "legendFormat": "Write Size"
    }
   ]
  },
  {
   "title": "Write Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EBS_VolumeWriteOps{VolumeId=~\"$VolumeId\"})",
     "legendFormat": "Write Operations"
    }
   ]
  },
  {
   "title": "Write Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EBS_VolumeTotalWriteTime_sum{VolumeId=~\"$VolumeId\"}) ",
     "legendFormat": "Write Time"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Volume Idle Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EBS_VolumeIdleTime{VolumeId=~\"$VolumeId\"}) by (VolumeId)",
     "legendFormat": "{{VolumeId}}"
    }
   ]
  },
  {
   "title": "Volume Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EBS_VolumeQueueLength{VolumeId=~\"$VolumeId\"}) by (VolumeId)",
     "legendFormat": "{{VolumeId}}"
    }
   ]
  },
  {
   "title": "Burst Balance by Volume ID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_EBS_BurstBalance{VolumeId=~\"$VolumeId\"}) by (VolumeId)",
     "legendFormat": "{{VolumeId}}"
    }
   ]
  },
  { "title": "Read/Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Read bytes per Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EBS_VolumeReadBytes{VolumeId=~\"$VolumeId\"}) by (VolumeId)",
     "legendFormat": "{{VolumeId}}"
    }
   ]
  },
  {
   "title": "Write bytes per Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EBS_VolumeWriteBytes{VolumeId=~\"$VolumeId\"}) by (VolumeId)",
     "legendFormat": "{{VolumeId}}"
    }
   ]
  },
  {
   "title": "Read Operations per Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EBS_VolumeReadOps{VolumeId=~\"$VolumeId\"}) by (VolumeId)",
     "legendFormat": "{{VolumeId}}"
    }
   ]
  },
  {
   "title": "Write Operations per Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EBS_VolumeWriteOps{VolumeId=~\"$VolumeId\"}) by (VolumeId)",
     "legendFormat": "{{VolumeId}}"
    }
   ]
  },
  {
   "title": "Total Read Time per Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EBS_VolumeTotalReadTime_sum{VolumeId=~\"$VolumeId\"}) by (VolumeId)",
     "legendFormat": "{{VolumeId}}"
    }
   ]
  },
  {
   "title": "Total Write Time per Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_EBS_VolumeTotalWriteTime_sum{VolumeId=~\"$VolumeId\"}) by (VolumeId)",
     "legendFormat": "{{VolumeId}}"
    }
   ]
  }
 ]
}