{
 "title": "RDS Dashboard by DB Instance Identifier",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbInstanceIdentifier",
    "label": "DB Instance Identifier",
    "query": {
     "query": "label_values(db_instance_identifier)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DB CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_rds_cpu_utilization_average{db_instance_identifier=~\"$dbInstanceIdentifier\",db_instance_identifier!=\"\"}) by (db_instance_identifier)",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_rds_deadlocks_sum{db_instance_identifier=~\"$dbInstanceIdentifier\",db_instance_identifier!=\"\"}) by (db_instance_identifier)",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "Connections (Max 3000)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_rds_database_connections_average{db_instance_identifier=~\"$dbInstanceIdentifier\",db_instance_identifier!=\"\"}) by (db_instance_identifier)",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "Row Lock Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_rds_row_lock_time_average{db_instance_identifier=~\"$dbInstanceIdentifier\",db_instance_identifier!=\"\"}) by (db_instance_identifier)",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "DB CPU Utilization % (All Role)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_rds_cpu_utilization_average{db_cluster_identifier!=\"\",role!=\"\"}) by (role,db_cluster_identifier)",
     "legendFormat": "{{role}}>>{{db_cluster_identifier}}"
    }
   ]
  }
 ]
}