{
 "title": "CloudWatch FSx Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "FileSystemId", "label": "Filesystem ID", "query": { "query": "label_values(FileSystemId)" } }
  ]
 },
 "panels": [
  {
   "title": "Filesystems",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count(amazonaws_com_AWS_FSx_DataReadBytes{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId))"
    }
   ]
  },
  {
   "title": "Minimum free capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "min(amazonaws_com_AWS_FSx_FreeDataStorageCapacity{FileSystemId=~\"$FileSystemId\"})"
    }
   ]
  },
  {
   "title": "Maximum metadata operations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(amazonaws_com_AWS_FSx_MetadataOperations{FileSystemId=~\"$FileSystemId\"})"
    }
   ]
  },
  {
   "title": "Read operations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_FSx_DataReadOperations{FileSystemId=~\"$FileSystemId\"})"
    }
   ]
  },
  {
   "title": "Bytes read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_FSx_DataReadBytes{FileSystemId=~\"$FileSystemId\"})"
    }
   ]
  },
  {
   "title": "Write operations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_FSx_DataWriteBytes{FileSystemId=~\"$FileSystemId\"})"
    }
   ]
  },
  {
   "title": "Bytes written",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_FSx_DataWriteBytes{FileSystemId=~\"$FileSystemId\"})"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "FSx Free Capacity by Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_FSx_FreeDataStorageCapacity{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId)",
     "legendFormat": "{{FileSystemId}}"
    }
   ]
  },
  {
   "title": "FSx Meta Operations by Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_FSx_MetadataOperations{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId)",
     "legendFormat": "{{FileSystemId}}"
    }
   ]
  },
  { "title": "Read/Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "FSx Data Read bytes by Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_FSx_DataReadBytes{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId)",
     "legendFormat": "{{FileSystemId}}"
    }
   ]
  },
  {
   "title": "FSx Data Write bytes by Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(amazonaws_com_AWS_FSx_DataWriteBytes{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId)",
     "legendFormat": "{{FileSystemId}}"
    }
   ]
  },
  {
   "title": "FSx Data Reads Operations by Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_FSx_DataReadOperations{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId)",
     "legendFormat": "{{FileSystemId}}"
    }
   ]
  },
  {
   "title": "FSx Data Write Operations by Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(amazonaws_com_AWS_FSx_DataWriteOperations{FileSystemId=~\"$FileSystemId\"}) by (FileSystemId)",
     "legendFormat": "{{FileSystemId}}"
    }
   ]
  }
 ]
}