{
 "title": "CloudWatch - Application Load Balancer",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "load_balancer", "label": "Load Balancer Name", "query": { "query": "label_values(load_balancer)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_application_elb_request_count_average{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "Target Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_application_elb_target_response_time_average{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_application_elb_active_connection_count_average{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "ActiveConnection - {{load_balancer}}"
    },
    {
     "expr": "avg(cloudwatch_aws_application_elb_new_connection_count_average{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "NewConnection - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Host Health",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_application_elb_healthy_host_count_average{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "Healthy Host - {{load_balancer}}"
    },
    {
     "expr": "avg(cloudwatch_aws_application_elb_un_healthy_host_count_average{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "UnHealthy Host - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "TLS Negotiation Error",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_application_elb_client_tls_negotiation_error_count_sum{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "ClientTlsNegotiationError - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "HTTP Code Target",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_application_elb_http_code_target_5xx_count_sum{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "HTTPCode_Target_5XX - {{load_balancer}}"
    },
    {
     "expr": "sum(cloudwatch_aws_application_elb_http_code_target_4xx_count_sum{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "HTTPCode_Target_4XX - {{load_balancer}}"
    },
    {
     "expr": "sum(cloudwatch_aws_application_elb_http_code_target_3xx_count_sum{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "HTTPCode_Target_3XX - {{load_balancer}}"
    },
    {
     "expr": "sum(cloudwatch_aws_application_elb_http_code_target_2xx_count_sum{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "HTTPCode_Target_2XX - - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Processed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_application_elb_grpc_request_count_sum{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "GrpcRequest - {{load_balancer}}"
    },
    {
     "expr": "avg(cloudwatch_aws_application_elb_non_sticky_request_count_average{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "NobStickyRequest - {{load_balancer}}"
    },
    {
     "expr": "avg(cloudwatch_aws_application_elb_grpc_request_count_sum{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "ProcessedBytes - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Rule Evaluations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_application_elb_rule_evaluations_sum{load_balancer=~\"$load_balancer\"}) by (load_balancer)",
     "legendFormat": "RuleEvaluations - {{load_balancer}}"
    }
   ]
  }
 ]
}