{
 "title": "CloudWatch - CloudFront",
 "description": "Visualize AWS CloudFront metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "distribution_id", "query": { "query": "label_values(distribution_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests and Error Rate",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "expr": "avg(cloudwatch_aws_cloud_front_cache_hit_rate_average{distribution_id=~\"$distribution_id\"}) by (distribution_id)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Cachhe Hit Rate - {{distribution_id}}",
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "4xxErrorRate / 5xxErrorRate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "expr": "avg(cloudwatch_aws_cloud_front_4xx_error_rate_average{distribution_id=~\"$distribution_id\"}) by (distribution_id)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "4xxErrorRate - {{distribution_id}}",
     "metricName": "4xxErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "expr": "avg(cloudwatch_aws_cloud_front_5xx_error_rate_average{distribution_id=~\"$distribution_id\"}) by (distribution_id)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "5xxErrorRate - {{distribution_id}}",
     "metricName": "5xxErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Requests and Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "expr": "sum(cloudwatch_aws_cloud_front_requests_sum{distribution_id=~\"$distribution_id\"}) by (distribution_id)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Requests - {{distribution_id}}",
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "expr": "avg(cloudwatch_aws_cloud_front_total_error_rate_average{distribution_id=~\"$distribution_id\"}) by (distribution_id)",
     "legendFormat": "ErrorRate - {{distribution_id}}"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "expr": "avg(cloudwatch_aws_cloud_front_cache_hit_rate_average{distribution_id=~\"$distribution_id\"}) by (distribution_id)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "CacheHitRate - {{distribution_id}}",
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "BytesDownloaded / BytesUploaded",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "expr": "sum(cloudwatch_aws_cloud_front_bytes_downloaded_average{distribution_id=~\"$distribution_id\"}) by (distribution_id)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "BytesDownloaded - {{distribution_id}}",
     "metricName": "BytesDownloaded",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "expr": "sum(cloudwatch_aws_cloud_front_bytes_uploaded_average{distribution_id=~\"$distribution_id\"}) by (distribution_id)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "BytesUploaded - {{distribution_id}}",
     "metricName": "BytesUploaded",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  }
 ]
}