{
 "title": "Host Metrics",
 "description": "Metric view designed for a single system since some graphs overlay multiple queries.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(system_uptime_total, host)"
    }
   },
   {
    "name": "disk_device",
    "query": {
     "query": "label_values(disk_used_percent{fstype!=\"rootfs\", host=\"$host\"}, device)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(net_bytes_sent{host=\"$host\"}, interface)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime_total{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Logged In Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_users{host=\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processes_total{host=\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_containers{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_cpus{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_total{host=\"$host\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100-cpu_usage_idle{host=\"$host\", cpu=\"cpu-total\"})"
    }
   ]
  },
  {
   "title": "CPU Total %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_user{host=\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "User"
    },
    {
     "expr": "cpu_usage_system{instance=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "System"
    },
    {
     "expr": "cpu_usage_idle{instance=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU Cores - User",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_user{host=\"$host\", cpu!=\"cpu-total\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Cores - System",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_system{host=\"$host\", cpu!=\"cpu-total\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_buffered{host=\"$host\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "mem_cached{host=\"$host\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "mem_free{host=\"$host\"}",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load1{host=\"$host\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "system_load5{host=\"$host\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "system_load15{host=\"$host\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "processes_blocked{host=\"$host\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "processes_dead{host=\"$host\"}",
     "legendFormat": "Dead"
    },
    {
     "expr": "processes_idle{host=\"$host\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "processes_paging{host=\"$host\"}",
     "legendFormat": "Paging"
    },
    {
     "expr": "processes_running{host=\"$host\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "processes_sleeping{host=\"$host\"}",
     "legendFormat": "Sleeping"
    },
    {
     "expr": "processes_stopped{host=\"$host\"}",
     "legendFormat": "Stopped"
    },
    {
     "expr": "processes_unknown{host=\"$host\"}",
     "legendFormat": "Unknown"
    },
    {
     "expr": "processes_zombies{host=\"$host\"}",
     "legendFormat": "Zombies"
    }
   ]
  },
  {
   "title": "Docker Run State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_n_containers_running{host=\"$host\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "docker_n_containers_stopped{host=\"$host\"}",
     "legendFormat": "Stopped"
    },
    {
     "expr": "docker_n_containers_paused{host=\"$host\"}",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "title": "Context Switch & Interrupt Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kernel_context_switches_total{host=\"$host\"}[5m])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "rate(kernel_interrupts_total{host=\"$host\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  { "title": "Disk  Device: $disk_device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }, "repeat": "disk_device" },
  {
   "title": "Disk used - $disk_device",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$host\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disk capacity - $disk_device",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_free{host=\"$host\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Free on {{path}}"
    },
    {
     "expr": "disk_used{host=\"$host\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Used on {{path}}"
    }
   ]
  },
  {
   "title": "Disk IO Time Rate - $disk_device",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_read_time_total{host=\"$host\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
     "legendFormat": "Read Time"
    },
    {
     "expr": "rate(diskio_write_time_total{host=\"$host\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
     "legendFormat": "Write Time"
    },
    {
     "expr": "rate(diskio_io_time_total{host=\"$host\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
     "legendFormat": "IO Time"
    }
   ]
  },
  {
   "title": "Inodes Free - $disk_device",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_inodes_free{host=\"$host\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "disk_inodes_used{host=\"$host\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Inodes - $disk_device",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_inodes_free{host=\"$host\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Free on {{path}}"
    },
    {
     "expr": "disk_inodes_used{host=\"$host\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Used on {{path}}"
    }
   ]
  },
  {
   "title": "Disk IO Bytes Rate - $disk_device",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_read_bytes_total{host=\"$host\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(diskio_write_bytes_total{host=\"$host\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
     "legendFormat": "Write Bytes"
    }
   ]
  }
 ]
}