{
 "title": "CloudWatch - Kafka",
 "description": "Example of a Selectable Local Kafka Dashboard for DC/OS 1.12\n\n- For Developers: Parameterized to an input-able Kafka Cluster Name\n- Only displays metrics for Brokers and Topics within a specified Kafka cluster\n",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Kafka Cluster Name:", "query": { "query": "label_values(cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Kafka Overview for $cluster_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster avg msg/sec (1m)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cloudwatch_aws_kafka_messages_in_per_sec_average{cluster_name=~\"$cluster_name\"}[1m])) by (cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Cluster avg msg/sec (5m)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cloudwatch_aws_kafka_messages_in_per_sec_average{cluster_name=~\"$cluster_name\"}[5m])) by (cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Cluster avg msg/sec (15m)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cloudwatch_aws_kafka_messages_in_per_sec_average{cluster_name=~\"$cluster_name\"}[15m])) by (cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Cluster avg msg/sec (1m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(cloudwatch_aws_kafka_messages_in_per_sec_average{cluster_name=~\"$cluster_name\"}[1m])) by (cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Cluster avg msg/sec (5m)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(cloudwatch_aws_kafka_messages_in_per_sec_average{cluster_name=~\"$cluster_name\"}[5m])) by (cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Cluster avg msg/sec (15m)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(cloudwatch_aws_kafka_messages_in_per_sec_average{cluster_name=~\"$cluster_name\"}[15m])) by (cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Disk Used per Agent",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "max by(host) (disk_used)", "legendFormat": "{{host}}" }
     ]
    },
    {
     "title": "Cluster avg msg/sec (1m) by Topic",
     "type": "timeseries",
     "description": "Average messages per second per Topic",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(cloudwatch_aws_kafka_messages_in_per_sec_average{cluster_name=~\"$cluster_name\",topic!=\"\"}[1m])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Cluster avg msg/sec (5m) by Topic",
     "type": "timeseries",
     "description": "Average messages per second per Topic",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(cloudwatch_aws_kafka_messages_in_per_sec_average{cluster_name=~\"$cluster_name\",topic!=\"\"}[5m])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Cluster avg msg/sec (15m) by Topic",
     "type": "timeseries",
     "description": "Average messages per second per Topic",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(cloudwatch_aws_kafka_messages_in_per_sec_average{cluster_name=~\"$cluster_name\",topic!=\"\"}[15m])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Number of Leaders per Broker",
     "type": "timeseries",
     "description": "Number of leaders on this broker. This should be mostly even across all brokers. If not, set auto.leader.rebalance.enable to true on all brokers in the cluster.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(cloudwatch_aws_kafka_leader_count_sum{cluster_name=~\"$cluster_name\"}) by (cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Heap Memory in Use",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(cloudwatch_aws_kafka_heap_memory_after_gc_sum{cluster_name=~\"$cluster_name\"}) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Partition Count Across Brokers",
     "type": "graph",
     "description": "Number of partitions on this broker. This should be mostly even across all brokers.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(cloudwatch_aws_kafka_partition_count_average{cluster_name=~\"$cluster_name\"}) by (cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Broker Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "ActiveControllerCount",
   "type": "stat",
   "description": "The first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero that lasts for more than a short period (< 1s) of time.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_kafka_active_controller_count_sum{cluster_name=~\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "In a healthy cluster, the number of in sync replicas (ISRs) should be exactly equal to the total number of replicas. If partition replicas fall too far behind their leaders, the follower partition is removed from the ISR pool, and you should see a corresponding increase in IsrShrinksPerSec. Since Kafka’s high-availability guarantees cannot be met without replication, investigation is certainly warranted should this metric value exceed zero for extended time periods.\n\nIf this metric has a value greater than 1 it means that data is not being replicated to enough number of brokers thereby increasing the probability of data loss.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cloudwatch_aws_kafka_under_replicated_partitions_maximum{cluster_name=~\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cloudwatch_aws_kafka_offline_partitions_count_maximum{cluster_name=~\"$cluster_name\"})  "
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cloudwatch_aws_kafka_global_partition_count_maximum{cluster_name=~\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Total Partition Count per Broker",
   "type": "timeseries",
   "description": "The first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero that lasts for more than a short period (< 1s) of time.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_kafka_global_partition_count_sum{cluster_name=~\"$cluster_name\"}) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Offline Partitions per Broker",
   "type": "timeseries",
   "description": "This value should be 0",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(cloudwatch_aws_kafka_offline_partitions_count_maximum{cluster_name=~\"$cluster_name\"}) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Kafka avg msg/sec (1m) per Broker",
   "type": "timeseries",
   "description": "Average messages per second per Kafka broker",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(cloudwatch_aws_kafka_messages_in_per_sec_average{cluster_name=~\"$cluster_name\",broker_id!=\"\"}[1m])) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Kafka avg msg/sec (5m) per Broker",
   "type": "timeseries",
   "description": "Average messages per second per Kafka broker",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cloudwatch_aws_kafka_messages_in_per_sec_average{cluster_name=~\"$cluster_name\",broker_id!=\"\"}[5m])) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Kafka avg msg/sec (15m) per Broker",
   "type": "timeseries",
   "description": "Average messages per second per Kafka broker",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum(rate(cloudwatch_aws_kafka_messages_in_per_sec_average{cluster_name=~\"$cluster_name\",broker_id!=\"\"}[15m])) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "All Bytes In (1min) per Broker",
   "type": "timeseries",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(cloudwatch_aws_kafka_bytes_in_per_sec_sum{cluster_name=~\"$cluster_name\"}[1m])) by(broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "All Bytes In (15min) per Broker",
   "type": "timeseries",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(cloudwatch_aws_kafka_bytes_in_per_sec_sum{cluster_name=~\"$cluster_name\"}[15m])) by(broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "All Bytes Out (1min) per Broker",
   "type": "timeseries",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(cloudwatch_aws_kafka_bytes_out_per_sec_sum{cluster_name=~\"$cluster_name\"}[1m])) by(broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "All Bytes Out (15min) per (Service / Broker)",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cloudwatch_aws_kafka_bytes_out_per_sec_sum{cluster_name=~\"$cluster_name\"}[15m])) by(broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  { "title": "Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Estimated Max Time Lag by Consumer group",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(cloudwatch_aws_kafka_estimated_max_time_lag_maximum{cluster_name=~\"$cluster_name\"}) by (consumer_group)",
     "legendFormat": "{{consumer_group}}"
    }
   ]
  },
  {
   "title": "Offset Max Time Lag by Consumer group",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(cloudwatch_aws_kafka_max_offset_lag_maximum{cluster_name=~\"$cluster_name\"}) by (consumer_group)",
     "legendFormat": "{{consumer_group}}"
    }
   ]
  },
  {
   "title": "Sum Offset Max Time Lag by Consumer group",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(cloudwatch_aws_kafka_sum_offset_lag_maximum{cluster_name=~\"$cluster_name\"}) by (consumer_group)",
     "legendFormat": "{{consumer_group}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Fetch Throttle Queue Size per Broker",
   "type": "timeseries",
   "description": "Size of the request queue. A congested request queue will not be able to process incoming or outgoing requests",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_kafka_fetch_throttle_queue_size_sum{cluster_name=~\"$cluster_name\"}) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Produce Throttle Queue Size per Broker",
   "type": "timeseries",
   "description": "Size of the request queue. A congested request queue will not be able to process incoming or outgoing requests",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_kafka_produce_throttle_queue_size_sum{cluster_name=~\"$cluster_name\"}) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Request Throttle Queue Size per Broker",
   "type": "timeseries",
   "description": "Size of the request queue. A congested request queue will not be able to process incoming or outgoing requests",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_kafka_request_throttle_queue_size_sum{cluster_name=~\"$cluster_name\"}) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Volume Queue Length per Broker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_kafka_volume_queue_length_sum{cluster_name=~\"$cluster_name\"}) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Average fetch consumer request queue time",
   "type": "piechart",
   "description": "Size of the request queue. A congested request queue will not be able to process incoming or outgoing requests",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_kafka_fetch_consumer_request_queue_time_ms_mean_average{cluster_name=~\"$cluster_name\"}) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Average fetch consumer response queue time",
   "type": "piechart",
   "description": "Size of the request queue. A congested request queue will not be able to process incoming or outgoing requests",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_kafka_fetch_consumer_response_queue_time_ms_mean_average{cluster_name=~\"$cluster_name\"}) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Average fetch follower request queue time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_kafka_fetch_follower_request_queue_time_ms_mean_average{cluster_name=~\"$cluster_name\"}) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Average fetch follower response queue time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_kafka_fetch_follower_response_queue_time_ms_mean_average{cluster_name=~\"$cluster_name\"}) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Average produce request queue time",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_kafka_produce_request_queue_time_ms_mean_average{cluster_name=~\"$cluster_name\"}) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Produce Total Time in sec (15min) per Broker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cloudwatch_aws_kafka_produce_total_time_ms_mean_sum{cluster_name=~\"$cluster_name\"}[15m])) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Produce Message Conversion Time in sec (15min) per Broker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cloudwatch_aws_kafka_produce_message_conversions_time_ms_mean_sum{cluster_name=~\"$cluster_name\"}[15m])) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Average produce response queue time",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_kafka_produce_response_queue_time_ms_mean_average{cluster_name=~\"$cluster_name\"}) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  {
   "title": "Produce Local Time in sec (15min) per Broker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cloudwatch_aws_kafka_produce_local_time_ms_mean_sum{cluster_name=~\"$cluster_name\"}[15m])) by (broker_id)",
     "legendFormat": "{{broker_id}}"
    }
   ]
  },
  { "title": "Network Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Network Request Rate / sec (15min) ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cloudwatch_aws_kafka_network_rx_packets_sum{cluster_name=~\"$cluster_name\"}[15m])) by(cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Network Processor Idle (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_kafka_network_processor_avg_idle_percent_sum{cluster_name=~\"$cluster_name\"}) by(cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  }
 ]
}