{
 "title": "CloudWatch - SQS",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "queue_name", "query": { "query": "label_values(queue_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Average number of messages sent",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_sqs_number_of_messages_sent_sum{queue_name=~\"$queue_name\"})"
    }
   ]
  },
  {
   "title": "Average number of messages sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_sqs_number_of_messages_sent_average{queue_name=~\"$queue_name\"}) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Average number of messages received",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_sqs_number_of_messages_received_sum{queue_name=~\"$queue_name\"})"
    }
   ]
  },
  {
   "title": "Average number of messages received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_sqs_number_of_messages_received_average{queue_name=~\"$queue_name\"}) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Average number of messages deleted",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_sqs_number_of_messages_deleted_sum{queue_name=~\"$queue_name\"})"
    }
   ]
  },
  {
   "title": "Average number of messages deleted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_sqs_number_of_messages_deleted_average{queue_name=~\"$queue_name\"}) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Average number of messages visible",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_sqs_approximate_number_of_messages_visible_sum{queue_name=~\"$queue_name\"})"
    }
   ]
  },
  {
   "title": "Average number of messages visible",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_sqs_approximate_number_of_messages_visible_average{queue_name=~\"$queue_name\"}) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Average number of messages not visible",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_sqs_approximate_number_of_messages_not_visible_sum{queue_name=~\"$queue_name\"})"
    }
   ]
  },
  {
   "title": "Average number of messages not visible",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 18 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_sqs_approximate_number_of_messages_not_visible_average{queue_name=~\"$queue_name\"}) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Average number of empty messages",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudwatch_aws_sqs_number_of_empty_receives_sum{queue_name=~\"$queue_name\"})"
    }
   ]
  },
  {
   "title": "Average number of empty messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_sqs_number_of_empty_receives_average{queue_name=~\"$queue_name\"}) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Average number of messages delayed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_sqs_approximate_number_of_messages_delayed_average{queue_name=~\"$queue_name\"}) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Average age of oldest message",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_sqs_approximate_age_of_oldest_message_average{queue_name=~\"$queue_name\"}) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Average message size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "avg(cloudwatch_aws_sqs_sent_message_size_average{queue_name=~\"$queue_name\"}) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  }
 ]
}