{
 "title": "Otel Host Metrics",
 "description": "Node Exporter Full Prometheus Dashboard",
 "tags": [ "linux" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cloud_region", "label": "Cloud Region", "query": { "query": "label_values(cloud_region)" } },
   { "name": "host_name", "label": "Host Name", "query": { "query": "label_values(host_name)" } }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(system_cpu_load_average_5m_1{host_name=\"$host_name\"}) / count(count(system_cpu_time_total{host_name=\"$host_name\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(system_cpu_load_average_15m{host_name=\"$host_name\"}) /  count(count(system_cpu_time_total{host_name=\"$host_name\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage_By{host_name=\"$host_name\",state=\"free\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "system_memory_usage_By{host_name=\"$host_name\",state=\"used\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(system_disk_io_By_total{host_name=\"$host_name\", direction=\"read\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(system_disk_io_By_total{host_name=\"$host_name\", direction=\"write\"})",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host_name)(rate(system_cpu_time_total{host_name=\"$host_name\", state=\"system\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (host_name)(rate(system_cpu_time_total{host_name=\"$host_name\", state=\"user\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum (rate(k8s_node_cpu_time_total{}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_usage_By{host_name=\"$host_name\", state=\"free\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "system_memory_usage_By{host_name=\"$host_name\", state=\"used\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(system_network_io_By_total{host_name=\"$host_name\",direction=\"receive\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(system_network_io_By_total{host_name=\"$host_name\",direction=\"transmit\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (sum(system_filesystem_usage_By{host_name=\"$host_name\",state=\"free\"} * 100) / sum(system_filesystem_usage_By{host_name=\"$host_name\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "CPU / Memory / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(system_cpu_time_total{host_name=\"$host_name\"}) by (state)",
     "legendFormat": "CPU used by sever type - {{state}}"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(system_memory_usage_By{host_name=\"$host_name\"}) by (state)",
     "legendFormat": "Memory used by sever type - {{state}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(system_filesystem_usage_By{host_name=\"$host_name\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Disk I/O Ops",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "avg(system_disk_operations__operations__total{host_name=\"$host_name\"}) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bps", "label": "bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "avg(rate(system_network_io_By_total{host_name=\"$host_name\"}[$__rate_interval])) by (device, direction) * 8",
     "legendFormat": "{{device}} - {{direction}}"
    }
   ]
  },
  { "title": "Otel Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Processes Executable",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(otelcol_process_cpu_seconds_total{host_name=\"$host_name\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Uptime Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(otelcol_process_uptime_total{host_name=\"$host_name\"}) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Otel Processes Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(otelcol_process_runtime_heap_alloc_bytes{host_name=\"$host_name\"}) by (service_name)",
     "legendFormat": "heap: {{service_name}}"
    },
    {
     "expr": "avg(rate(otelcol_process_runtime_total_sys_memory_bytes{host_name=\"$host_name\"}[$__rate_interval])) by (service_name)",
     "legendFormat": "system: {{service_name}}"
    },
    {
     "expr": "avg(rate(otelcol_process_runtime_total_alloc_bytes_total{host_name=\"$host_name\"}[$__rate_interval])) by (service_name)",
     "legendFormat": "Toatl Allocated: {{service_name}}"
    },
    {
     "expr": "avg(otelcol_process_memory_rss{host_name=\"$host_name\"}) by (service_name)",
     "legendFormat": "rss: {{service_name}}"
    }
   ]
  }
 ]
}