{
 "title": "K8s Cluster Resources",
 "tags": [ "OpenTelemetry" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster_name)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(container_cpu_time_s_total{cluster_name=\"$cluster\"}, k8s_node_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_time_s_total{cluster_name=\"$cluster\"}, k8s_namespace_name)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(container_cpu_time_s_total{cluster_name=\"$cluster\"}, k8s_deployment_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_time_s_total{cluster_name=\"$cluster\"}, k8s_pod_name)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_time_s_total{cluster_name=\"$cluster\"}, k8s_container_name)"
    }
   },
   {
    "name": "replicaset",
    "query": {
     "query": "label_values(k8s_replicaset_desired_1{cluster_name=\"$cluster\"}, k8s_replicaset_name)"
    }
   },
   {
    "name": "daemonset",
    "query": {
     "query": "label_values(k8s_daemonset_ready_nodes_1{cluster_name=\"$cluster\"}, k8s_daemonset_name)"
    }
   },
   {
    "name": "statefulset",
    "query": {
     "query": "label_values(k8s_statefulset_desired_pods_1{cluster_name=\"$cluster\"}, k8s_statefulset_name)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(k8s_job_desired_successful_pods_1{cluster_name=\"$cluster\"},k8s_job_name)"
    }
   },
   {
    "name": "cron_job",
    "query": {
     "query": "label_values(k8s_cronjob_active_jobs_1{cluster_name=\"$cluster\"},k8s_cronjob_name)"
    }
   },
   {
    "name": "hpa",
    "query": {
     "query": "label_values(k8s_hpa_desired_replicas_1{cluster_name=\"$cluster\"},k8s_hpa_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(k8s_pod_cpu_time_total{cluster_name!=\"\"}) by (cluster_name))"
      }
     ]
    },
    {
     "title": "Namespace",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(k8s_pod_cpu_time_total{cluster_name=~\"$cluster\",k8s_namespace_name!=\"\"}) by (k8s_namespace_name))"
      }
     ]
    },
    {
     "title": "Node",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(k8s_pod_cpu_time_total{cluster_name=~\"$cluster\",k8s_node_name!=\"\"}) by (k8s_node_name))"
      }
     ]
    },
    {
     "title": "Deployment",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(k8s_pod_cpu_time_total{cluster_name=~\"$cluster\",k8s_deployment_name!=\"\"}) by (k8s_deployment_name))"
      }
     ]
    },
    {
     "title": "Demonset",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(container_cpu_time_s_total{cluster_name=~\"$cluster\",k8s_daemonset_name!=\"\"}) by (k8s_daemonset_name))"
      }
     ]
    },
    {
     "title": "Service",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(container_cpu_time_s_total{cluster_name=~\"$cluster\",cx_subsystem_name!=\"\"}) by (cx_subsystem_name))"
      }
     ]
    },
    {
     "title": "Pod",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(k8s_pod_cpu_time_total{cluster_name=~\"$cluster\",k8s_pod_name!=\"\"}) by (k8s_pod_name))"
      }
     ]
    },
    {
     "title": "Container",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(container_cpu_time_s_total{cluster_name=~\"$cluster\",k8s_container_name!=\"\"}) by (k8s_container_name))"
      }
     ]
    }
   ]
  },
  {
   "title": "Event",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes events per pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "regarding.name.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "coralogix.timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "coralogix.metadata.applicationName:\"kube-system\" AND coralogix.metadata.subsystemName:\"kube-events\"",
       "timeField": "coralogix.timestamp"
      }
     ]
    },
    {
     "title": "Kubernetes events per pod",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "coralogix.metadata.applicationName:\"kube-system\" AND coralogix.metadata.subsystemName:\"kube-events\"",
       "timeField": "coralogix.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Most cpu intensive pods",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(k8s_pod_cpu_utilization_1{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\", k8s_pod_name=~\"$pod\"}) by (k8s_pod_name)",
       "legendFormat": "{{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Most memory intensive pods",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((avg (k8s_pod_memory_working_set_By{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\", k8s_pod_name=~\"$pod\"}) by (k8s_pod_name))/ on (k8s_pod_name)(avg (k8s_pod_memory_usage_By{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\", k8s_pod_name=~\"$pod\"}) by (k8s_pod_name))*100) by (k8s_pod_name)",
       "legendFormat": "{{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "CPU utilization per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(k8s_node_cpu_utilization_1{cluster_name=~\"$cluster\",k8s_node_name=~\"$node\"}) by (k8s_node_name)",
       "legendFormat": "{{k8s_node_name}}"
      }
     ]
    },
    {
     "title": "Memory usage per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(k8s_node_filesystem_usage_By{cluster_name=~\"$cluster\",k8s_node_name=~\"$node\"}) by (k8s_node_name)",
       "legendFormat": "{{k8s_node_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods for $deployment deployment",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(container_cpu_time_s_total{cluster_name=~\"$cluster\",k8s_deployment_name=~\"$deployment\",k8s_pod_name!=\"\"}) by (k8s_pod_name))"
      }
     ]
    },
    {
     "title": "Pods for $namespace namespace",
     "type": "graph",
     "gridPos": { "h": 10, "w": 9, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(count(container_cpu_time_s_total{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\",k8s_pod_name!=\"\"}) by (k8s_namespace_name))"
      }
     ]
    },
    {
     "title": "Pods for $deployment deployment",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 15, "y": 4 },
     "targets": [
      {
       "expr": "count(count(container_cpu_time_s_total{cluster_name=~\"$cluster\",k8s_deployment_name=~\"$deployment\",k8s_pod_name!=\"\"}) by (k8s_deployment_name))"
      }
     ]
    },
    {
     "title": "Pods for $namespace namespace",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(container_cpu_time_s_total{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\",k8s_pod_name!=\"\"}) by (k8s_pod_name))"
      }
     ]
    },
    {
     "title": "Pods for $node node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "count(count(container_cpu_time_s_total{cluster_name=~\"$cluster\",k8s_node_name=~\"$node\",k8s_pod_name!=\"\"}) by (k8s_node_name))"
      }
     ]
    },
    {
     "title": "CrashloopBackOff by Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "regarding.name.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "coralogix.timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "_exists_:reason AND reason:\"BackOff.*\"",
       "timeField": "coralogix.timestamp"
      }
     ]
    },
    {
     "title": "Pod state count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "reason.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "coralogix.timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "_exists_:reason AND _exists_: \"regarding.name\"",
       "timeField": "coralogix.timestamp"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_time_s_total{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\", k8s_container_name=~\"$container\"}[$__rate_interval])) by (k8s_container_name)",
       "legendFormat": "{{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Memory request",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(k8s_container_memory_request{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\", k8s_container_name=~\"$container\"}) by (k8s_container_name)",
       "legendFormat": "{{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(container_memory_usage_By{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\", k8s_container_name=~\"$container\"}) by (k8s_container_name)",
       "legendFormat": "{{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Memory Major Page faults",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(increase(container_memory_major_page_faults_1{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\", k8s_container_name=~\"$container\"}[$__rate_interval])) by (k8s_container_name)",
       "legendFormat": "{{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(container_cpu_utilization_1{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\", k8s_container_name=~\"$container\"}) by (k8s_container_name)",
       "legendFormat": "{{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "File System",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_filesystem_capacity_By{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\", k8s_container_name=~\"$container\"}[$__rate_interval])) by (k8s_container_name)",
       "legendFormat": "Capacity: {{k8s_container_name}}"
      },
      {
       "expr": "sum(rate(container_filesystem_available_By{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\", k8s_container_name=~\"$container\"}[$__rate_interval])) by (k8s_container_name)",
       "legendFormat": "Available: {{k8s_container_name}}"
      },
      {
       "expr": "sum(rate(container_filesystem_usage_By{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\", k8s_container_name=~\"$container\"}[$__rate_interval])) by (k8s_container_name)",
       "legendFormat": "Usage: {{k8s_container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Daemonset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ready",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_daemonset_ready_nodes_1{cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", k8s_daemonset_name=~\"$daemonset\"})"
      }
     ]
    },
    {
     "title": "Ready",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 5 },
     "targets": [
      {
       "expr": "sum(k8s_daemonset_ready_nodes_1{cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", k8s_daemonset_name=~\"$daemonset\"}) by (k8s_daemonset_name)",
       "legendFormat": "{{k8s_daemonset_name}}"
      }
     ]
    },
    {
     "title": "Desired",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_daemonset_desired_scheduled_nodes_1{cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", k8s_daemonset_name=~\"$daemonset\"})"
      }
     ]
    },
    {
     "title": "Desired",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "targets": [
      {
       "expr": "sum(k8s_daemonset_desired_scheduled_nodes_1{cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\", k8s_daemonset_name=~\"$daemonset\"}) by (k8s_daemonset_name)",
       "legendFormat": "{{k8s_daemonset_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Desired",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_deployment_desired_1{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment desired",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 6 },
     "targets": [
      {
       "expr": "count(k8s_deployment_desired_1{cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\"}) by (k8s_deployment_name)",
       "legendFormat": "{{k8s_deployment_name}}"
      }
     ]
    },
    {
     "title": "Available",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_deployment_available_1{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment desired",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 6 },
     "targets": [
      {
       "expr": "count(k8s_deployment_available_1{cluster_name=~\"$cluster\", k8s_namespace_name=~\"$namespace\"}) by (k8s_deployment_name)",
       "legendFormat": "{{k8s_deployment_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replicaset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Desired",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_replicaset_desired_1{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\",k8s_replicaset_name=~\"$replicaset\"})"
      }
     ]
    },
    {
     "title": "Desired",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 7 },
     "targets": [
      {
       "expr": "sum(k8s_replicaset_desired_1{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\",k8s_replicaset_name=~\"$replicaset\"}) by (k8s_replicaset_name)",
       "legendFormat": "{{k8s_replicaset_name}}"
      }
     ]
    },
    {
     "title": "Available",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_replicaset_available_1{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\",k8s_replicaset_name=~\"$replicaset\"})"
      }
     ]
    },
    {
     "title": "Available",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
     "targets": [
      {
       "expr": "sum(k8s_replicaset_available_1{cluster_name=~\"$cluster\",k8s_namespace_name=~\"$namespace\",k8s_replicaset_name=~\"$replicaset\"}) by (k8s_replicaset_name)",
       "legendFormat": "{{k8s_replicaset_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statefulset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_statefulset_current_pods_1{cluster_name=~\"$cluster\",k8s_statefulset_name=~\"$statefulset\"})"
      }
     ]
    },
    {
     "title": "Desired",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_statefulset_desired_pods_1{cluster_name=~\"$cluster\",k8s_statefulset_name=~\"$statefulset\"})"
      }
     ]
    },
    {
     "title": "Ready",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_statefulset_ready_pods_1{cluster_name=~\"$cluster\",k8s_statefulset_name=~\"$statefulset\"})"
      }
     ]
    },
    {
     "title": "Updated",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_statefulset_updated_pods_1{cluster_name=~\"$cluster\",k8s_statefulset_name=~\"$statefulset\"})"
      }
     ]
    },
    {
     "title": "Updated",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum(k8s_statefulset_current_pods_1{cluster_name=~\"$cluster\",k8s_statefulset_name=~\"$statefulset\"})",
       "legendFormat": "Current"
      },
      {
       "expr": "sum(k8s_statefulset_desired_pods_1{cluster_name=~\"$cluster\",k8s_statefulset_name=~\"$statefulset\"})",
       "legendFormat": "Desired"
      },
      {
       "expr": "sum(k8s_statefulset_ready_pods_1{cluster_name=~\"$cluster\",k8s_statefulset_name=~\"$statefulset\"})",
       "legendFormat": "Ready"
      },
      {
       "expr": "sum(k8s_statefulset_updated_pods_1{cluster_name=~\"$cluster\",k8s_statefulset_name=~\"$statefulset\"})",
       "legendFormat": "Updated"
      }
     ]
    }
   ]
  },
  {
   "title": "Job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_job_active_pods_1{cluster_name=~\"$cluster\",k8s_job_name=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Desired successful",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_job_desired_successful_pods_1{cluster_name=~\"$cluster\",k8s_job_name=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Failed",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_job_failed_pods_1{cluster_name=~\"$cluster\",k8s_job_name=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Max parallel",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_job_max_parallel_pods_1{cluster_name=~\"$cluster\",k8s_job_name=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Succssful",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_job_successful_pods_1{cluster_name=~\"$cluster\",k8s_job_name=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Job by Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
     "targets": [
      {
       "expr": "sum(k8s_job_active_pods_1{cluster_name=~\"$cluster\",k8s_job_name=~\"$job\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(k8s_job_desired_successful_pods_1{cluster_name=~\"$cluster\",k8s_job_name=~\"$job\"})",
       "legendFormat": "Desired"
      },
      {
       "expr": "sum(k8s_job_failed_pods_1{cluster_name=~\"$cluster\",k8s_job_name=~\"$job\"})",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(k8s_job_max_parallel_pods_1{cluster_name=~\"$cluster\",k8s_job_name=~\"$job\"})",
       "legendFormat": "Max Parallel"
      },
      {
       "expr": "sum(k8s_job_successful_pods_1{cluster_name=~\"$cluster\",k8s_job_name=~\"$job\"})",
       "legendFormat": "Successful"
      }
     ]
    }
   ]
  },
  {
   "title": "Cronjob",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_cronjob_active_jobs_1{cluster_name=~\"$cluster\",k8s_cronjob_name=~\"$cron_job\"})"
      }
     ]
    },
    {
     "title": "All",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 10 },
     "targets": [
      {
       "expr": "sum(k8s_cronjob_active_jobs_1{cluster_name=~\"$cluster\",k8s_cronjob_name=~\"$cron_job\"}) by (k8s_cronjob_name)",
       "legendFormat": "{{k8s_cronjob_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HPA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Desired",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_hpa_desired_replicas_1{cluster_name=~\"$cluster\",k8s_hpa_name=~\"$hpa\"})"
      }
     ]
    },
    {
     "title": "Desired",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 11 },
     "targets": [
      {
       "expr": "sum(k8s_hpa_desired_replicas_1{cluster_name=~\"$cluster\",k8s_hpa_name=~\"$hpa\"}) by (k8s_hpa_name )",
       "legendFormat": "{{k8s_hpa_name}}"
      }
     ]
    },
    {
     "title": "Avilable",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_hpa_current_replicas_1{cluster_name=~\"$cluster\",k8s_hpa_name=~\"$hpa\"})"
      }
     ]
    },
    {
     "title": "Avilable",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 11 },
     "targets": [
      {
       "expr": "sum(k8s_hpa_current_replicas_1{cluster_name=~\"$cluster\",k8s_hpa_name=~\"$hpa\"}) by (k8s_hpa_name )",
       "legendFormat": "{{k8s_hpa_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O & Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network in per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(k8s_node_network_io_By_total{cluster_name=~\"$cluster\",k8s_node_name=~\"$node\", direction=\"receive\"}) by (host_name)",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Network out per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(k8s_node_network_io_By_total{cluster_name=~\"$cluster\",k8s_node_name=~\"$node\", direction=\"transmit\"}) by (host_name)",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Disk writes per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(system_disk_io_By_total{cluster_name=~\"$cluster\",k8s_node_name=~\"$node\", direction=\"write\"}) by (host_name)",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Disk writes per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(system_disk_io_By_total{cluster_name=~\"$cluster\",k8s_node_name=~\"$node\", direction=\"write\"}) by (host_name)",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Network errors per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(k8s_node_network_errors_1_total{cluster_name=~\"$cluster\",k8s_node_name=~\"$node\"}) by (host_name)",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Network errors per pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(k8s_pod_network_errors_1_total{cluster_name=~\"$cluster\",k8s_deployment_name=~\"$deployment\", k8s_namespace_name=~\"$node\", k8s_namespace_name=~\"$node\"}) by (k8s_pod_name)",
       "legendFormat": "{{k8s_pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}